<template>
  <div>
    <!-- <div class="title">
      <h2>福佬歌謠篇</h2>
    </div>
    <hr> -->
    <p class="firstRow"></p>
    <!-- <h3>福佬歌謠 團體名錄索引</h3> -->
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人/ 聯絡人</th>
          <th>地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>雨韻合唱團</td>
          <td>陳建宏</td>
          <td>
            基隆市安樂區樂利三街205號7樓
            <br>02-2425-3518
          </td>
          <td>
            <a target="_" href="http://www.yuyun.org.tw/yuyun/index.php/yuyun-about"
            >連結</a>
          </td>
          <td>1960年成立於基隆市，是基隆第一個社會合唱團體。</td>
        </tr>
        <tr>
          <td>基隆市教師合唱團</td>
          <td>團長 梁碧霞</td>
          <td>
            基隆市仁愛區仁二路139號
            <br>0933-883-578
          </td>
          <td></td>
          <td>成立於1976年，由一群喜愛音樂的教師所組成，目前由林右昌市長擔任名譽團長。</td>
        </tr>
        <tr>
          <td>基隆啄木鳥合唱團</td>
          <td>陳吉宗</td>
          <td>
            基隆市仁愛區仁二路58號
            <br>02-2423-4884
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pages/category/Performing-Arts/基隆市啄木鳥合唱團粉絲團-516315805193598/"
            >連結</a>
          </td>
          <td>1985年成立於基隆，是由一群熱愛合唱的男士所組成。成立宗旨為「以雄壯渾厚、優美溫醇之男聲合唱，來洗滌人心，並形塑社會之善良風氣」。</td>
        </tr>
        <tr>
          <td>基隆愛樂合唱團</td>
          <td>莊瑾潔</td>
          <td>
            基隆市仁愛區仁二路119巷13-4號1樓
            <br>02-2425-5289
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/KeelungPhilharmonicChoir/"
            >連結</a>
          </td>
          <td>成立於1975年，前身為基隆商工校友合唱團，團員來自社會各階層熱愛合唱藝術的朋友們。</td>
        </tr>
        <tr>
          <td>暖韻合唱團</td>
          <td>潭國才</td>
          <td>
            基隆市暖暖區過港路92號
            <br>02-2458-1854
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pages/category/Community/98-Nuan-Yun-Choir-119575801444376/"
            >連結</a>
          </td>
          <td>成立於2001年，成立宗旨為「為推廣社區音樂文化、合唱藝術、凝聚社區情感。」</td>
        </tr>
        <tr>
          <td>水溝蓋樂團</td>
          <td>周睿德</td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/DitchCover/">連結</a>
          </td>
          <td>成立於臺北市的創作樂團</td>
        </tr>
        <tr>
          <td>長春花樂團</td>
          <td>陳明章 阿桃家族</td>
          <td>
            臺北市北投區開明街71號
            <br>02-2893-3088
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/長春花樂團98-1061906727227527/"
            >連結</a>
          </td>
          <td>成立於2015年。長春花樂團成員全由來自各地的臺灣月琴民謠協會學員所組成。</td>
        </tr>
        <tr>
          <td>臺北愛樂婦女合唱團</td>
          <td>王舒慧</td>
          <td>
            臺北市大安區敦化南路一段233巷28號B1
            <br>02-2773-3691#135
          </td>
          <td>
            <a target="_" href="http://twss.pixnet.net/blog">連結</a>
          </td>
          <td>成立於2002年，以「唱到八十，永遠十八」為宗旨，期盼「以歌會友」。</td>
        </tr>
        <tr>
          <td>臺灣月琴民謠協會</td>
          <td>陳明章</td>
          <td>
            臺北市北投區開明街71號
            <br>02-2893-3088
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Taiwan.yueqin/"
            >連結</a>
          </td>
          <td>成立於2009年，發起人為陳明章，他集合熱衷致力推廣月琴之會員，讓臺灣的國民樂器「月琴」能繼續被傳承與演奏。</td>
        </tr>
        <tr>
          <td>蝦米視障人聲樂團</td>
          <td>代表人 朱元雷<br>
              公關 劉靜惠
          </td>
          <td>
            臺北市內湖區麗山里內湖路一段387巷5號
            <br>02-2920-9028
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/shiamishiami/">連結</a>
          </td>
          <td>2011年7月由臺灣合唱音樂中心，招募多位愛唱歌的視障朋友，展開「用聲音看世界」－視障人聲樂團的培訓計畫。</td>
        </tr>
        <tr>
          <td>田園樂府</td>
          <td>簡上仁</td>
          <td>
            新北市淡水區紅樹林路195號8樓
            <br>02-3758-0272
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TWS999/"
            >連結</a>
          </td>
          <td>1983年簡上仁創立</td>
        </tr>
        <tr>
          <td>楊秀卿說唱藝術團</td>
          <td>楊火土</td>
          <td>
            新北市汐止區汐萬路二段37巷3號3樓
            <br>02-2646-3947
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/showking317/"
            >連結</a>
          </td>
          <td>2010年成立，楊秀卿為國家指定登錄重要傳統藝術說唱保存者。</td>
        </tr>
        <tr>
          <td>臺北華新兒童合唱團</td>
          <td>方素貞</td>
          <td>
            新北市板橋區文化路二段90號地下1樓
            <br>0952-289-124
          </td>
          <td>
            <a target="_" href="https://www.huashincc.org/">連結</a>
          </td>
          <td>1988年春，華新建設公司與新北市政府文化局共同成立。</td>
        </tr>
        <tr>
          <td>台灣合唱音樂中心</td>
          <td>陳雲紅</td>
          <td>
            新北市中和區中和路366號8樓之3
            <br>02-2920-9028
          </td>
          <td>
            <a target="_" href="http://www.tcmc.org.tw/index.php">連結</a>
          </td>
          <td>成立於2000年，期望立足臺灣，展望世界，推廣合唱發展。</td>
        </tr>
        <tr>
          <td>臺灣說唱藝術工作室</td>
          <td>周定邦</td>
          <td>
            臺南市府前路2段258巷29弄24號
            <br>0929-672-033
          </td>
          <td>
            <a target="_" href="http://tengpang2762.pixnet.net/blog">連結</a>
          </td>
          <td>
            成立於2000年，宗旨為「傳承、推廣
            <em>臺灣</em>唸歌和恆春民謠」。
          </td>
        </tr>
        <tr>
          <td>新竹市立薔薇婦女合唱團</td>
          <td>林香吟</td>
          <td>
            0921-980-166
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pages/category/Performing-Arts/98-217067061811495/"
            >連結</a>
          </td>
          <td>已成立30年，由何桂華領軍與指導，一步一腳印的為鄉土歌謠推展努力不懈。</td>
        </tr>
        <tr>
          <td>微笑唸歌團</td>
          <td>儲見智</td>
          <td>
            臺中市北區錦中街25號
            <br>0953-724-857
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwansmile/">連結</a>
          </td>
          <td>成立於2011年，創辦人為儲見智與林恬安，以傳承推廣唸歌文化為主要宗旨，藉由唸歌的演出、展覽、教學、演講等方式，傳達臺語說唱藝術的理念。</td>
        </tr>
        <tr>
          <td>旭陽民俗車鼓劇團</td>
          <td>吳現山</td>
          <td>雲林縣土庫鎮</td>
          <td></td>
          <td>成立於1973年</td>
        </tr>
        <tr>
          <td>打狗亂歌團</td>
          <td>嚴詠能</td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/takaorun/">連結</a><br>
            <a target="_" href="mailto:runran1970123@gmail.com">連結</a>
          </td>
          <td>打狗亂歌團是以本土創作及母語歌謠走唱為業，每位樂手玩的音樂不同，創作題材不同，曲風不一，所以他們自取名為亂歌團，不過亂歌團的「亂」，臺語同音字為「戀」，樂團希望藉由創作跟土地談戀愛。</td>
        </tr>
        <tr>
          <td>恆春民謠促進會</td>
          <td>陳麗萍</td>
          <td>
            屏東縣恆春鎮中正路146號
            <br>08-889-8166
          </td>
          <td>
            <a target="_" href="http://web.hcps.ptc.edu.tw/cyberfair2006/G/g2.htm"
            >連結</a>
          </td>
          <td>高李正姬任團長，總幹事趙振英。</td>
        </tr>
        <tr>
          <td>恆春民謠館</td>
          <td>屏東縣政府</td>
          <td>
            屏東縣恆春鎮恆南路168號
            <br>08-888-0293
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pages/category/Travel-Service/恆春民謠館-424690274297349/"
            >連結</a>
          </td>
          <td>2009年揭牌啟用。2008年屏東縣政府向恆春旅遊醫院租用舊有宿舍作為「恆春民謠館」。</td>
        </tr>
        <tr>
          <td>滿州民謠協進會</td>
          <td>滿州鄉公所</td>
          <td>
            屏東縣滿州鄉
            <em>滿州</em>村中山路43號
            <br>08-880-1105
          </td>
          <td>
            <a target="_" href="https://www.pthg.gov.tw/townmto/Content_List.aspx?n=1D48F4EE0338DF0B"
            >連結</a>
          </td>
          <td>1981年立案</td>
        </tr>
        <tr>
          <td>滿州民謠館</td>
          <td>滿州鄉公所</td>
          <td>
            屏東縣滿州鄉
            <em>滿州</em>村中山路43號
            <br>08-880-1105
          </td>
          <td>
            <a target="_" href="https://www.pthg.gov.tw/townmto/Content_List.aspx?n=1D48F4EE0338DF0B"
            >連結</a>
          </td>
          <td>2018年2月16日開幕</td>
        </tr>
        <tr>
          <td>不老梅說唱藝術</td>
          <td>6位素人說唱者</td>
          <td></td>
          <td></td>
          <td>由6位素人說唱者組成，為的是證明「人老心不老」，臺灣傳統說唱傳承是人人可以有所貢獻的。</td>
        </tr>
      </tbody>
    </table>
    <br>
    <!-- <h3>福佬歌謠 個人名錄索引</h3> -->
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:10%">名稱</th>
          <th style="width:18%">地址/電話</th>
          <th style="width:15%">其他聯絡方式</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>丁秀津</td>
          <td>臺北市</td>
          <td>
            <a target="_" href="https://www.facebook.com/Melodysyueqin/"
            >連結</a>
          </td>
          <td>唸歌仔藝人。文化部指定「重要無形文化資產保存者」楊秀卿之第2屆傳習藝生。</td>
        </tr>
        <tr>
          <td>邵大倫</td>
          <td>
            臺北市
            <br>0931-123-075
          </td>
          <td></td>
          <td>
            1980-，臺灣男歌手、廣播DJ、電視節目主持人，2017年廣播金鐘獎最佳流行音樂節目主持人獎。
          </td>
        </tr>
        <tr>
          <td>紀露霞</td>
          <td>臺北市萬華區</td>
          <td></td>
          <td>1936-，臺語流行歌手，2017年獲得第28屆金曲獎「特別貢獻獎」。</td>
        </tr>
        <tr>
          <td>陳明章</td>
          <td>臺北市北投區</td>
          <td></td>
          <td>
            1956-，音樂創作人、音樂製作人、歌手、吉他與月琴演奏家、黑膠唱片收藏家。1987年法國南特影展上，《戀戀風塵》獲得最佳電影配樂，之後便經常為電影、紀錄片製作音樂。
          </td>
        </tr>
        <tr>
          <td>陳維斌</td>
          <td>臺北市</td>
          <td>
            <a target="_" href="https://www.facebook.com/DenxTaiwanMusic/"
            >連結</a>
          </td>
          <td>臺語歌曲詞曲作家、醫生。</td>
        </tr>
        <tr>
          <td>鄭美</td>
          <td>臺北市</td>
          <td></td>
          <td>唸歌仔藝人。文化部指定「重要無形文化資產保存者」楊秀卿之第1屆傳習藝生。</td>
        </tr>
        <tr>
          <td>林垂立</td>
          <td>
            新北市瑞芳區
          </td>
          <td></td>
          <td>臺語歌曲製作人、詞曲作者。為人熟悉的代表作品有〈車站〉、〈春夏秋冬〉等。</td>
        </tr>
        <tr>
          <td>陳美珠</td>
          <td>新北市新店區</td>
          <td></td>
          <td>1927-，唸歌仔藝人。2016年和陳寶貴同時被新北市政府指定登錄為新北市說唱傳統表演藝術保存者。</td>
        </tr>
        <tr>
          <td>楊秀卿</td>
          <td>新北市汐止區</td>
          <td></td>
          <td>1935-，國寶級唸歌仔藝人。1989年獲教育部頒發民族說唱藝術「薪傳獎」，2007年獲國家文化藝術基金會頒發第11屆「國家文藝獎」，2009年獲文建會指定為「第一屆重要傳統藝術說唱類保存者」，同年亦成為臺北縣市政府合聘的「第一屆臺北傳統藝術榮譽藝師」，在臺灣說唱藝術界獲得至高無上的榮譽。2010年文化部文化資產局指定其為「重要無形文化資產」保存藝師。</td>
        </tr>
        <tr>
          <td>簡上仁</td>
          <td>
            新北市淡水區
            <br>02-3758-0272
          </td>
          <td></td>
          <td>
            1948-，詞曲創作、演唱者。民族音樂研究者。長期致力於臺灣本土音樂之採集、整理、創作及推展工作，1983年成立「田園樂府」樂團並擔任團長至今。曾獲關懷臺灣人文社會貢獻獎(1991)、第廿四屆中興文藝獎章音樂獎(2001)、國立清華大學傑出教學獎(2002)、第11屆全球華人藝術文化薪傳獎(2004)等。
          </td>
        </tr>
        <tr>
          <td>陳寶貴</td>
          <td>新竹縣</td>
          <td></td>
          <td>
            1939-，唸歌仔說唱藝人。2016年和陳美珠同時被新北市政府指定登錄為新北市說唱傳統表演藝術保存者。
          </td>
        </tr>
        <tr>
          <td>林恬安</td>
          <td>臺中市潭子區</td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwansmile/">連結</a>
          </td>
          <td>擅長唸歌仔。與儲見智共同成立微笑唸歌團。文化部指定「重要無形文化資產保存者」楊秀卿之第2屆傳習藝生。</td>
        </tr>
        <tr>
          <td>儲見智</td>
          <td>
            臺中市潭子區
            <br>0953-724-857
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwansmile/">連結</a>
          </td>
          <td>1976-，擅長唸歌仔，微笑唸歌團團長。文化部指定「重要無形文化資產保存者」楊秀卿之第2屆傳習藝生。</td>
        </tr>
        <tr>
          <td>文夏</td>
          <td>臺南市麻豆區</td>
          <td></td>
          <td>
            1928-，本名王瑞河。知名臺語流行歌手。2012年第23屆金曲獎獲頒特別貢獻獎。
          </td>
        </tr>
        <tr>
          <td>周定邦</td>
          <td>臺南市將軍區</td>
          <td></td>
          <td>1958-，擅長說唱藝術。臺灣說唱藝術工作室團長。蒐集臺灣唸歌文物、展演、推廣臺灣唸歌藝術，創作及出版臺灣歌仔冊、CD、DVD，堅心傳承唸歌藝術。</td>
        </tr>
        <tr>
          <td>陳和平</td>
          <td>臺南市</td>
          <td></td>
          <td>1948-，臺灣流行歌曲創作人、製作人。曾任職海山唱片公司宣傳部主任，負責製作臺語歌曲、製作百場大型電臺聽友聯歡大會。目前擔任麒文形象設計事業有限公司董事長、社團法人「臺灣音樂著作權人聯合總會」董事。</td>
        </tr>
        <tr>
          <td>嚴詠能</td>
          <td>臺南市新化區</td>
          <td></td>
          <td>
            1970-，歌手。打狗亂歌團團長。獲第21屆金曲獎最佳臺語專輯獎，並入圍第21屆金曲獎最佳臺語男歌手獎。
          </td>
        </tr>
        <tr>
          <td>蔣為文</td>
          <td>高雄縣岡山區</td>
          <td></td>
          <td>
            1971-，臺灣語言學家、作家、臺語文運動的推行者及越南研究專家。國立成功大學臺灣文學系教授、臺灣語文測驗中心主任等。
          </td>
        </tr>
        <tr>
          <td>金澎</td>
          <td>屏東縣</td>
          <td></td>
          <td>
            1944-，本名陳聰仁。臺灣男藝人。有「歌壇活字典」之稱號。
          </td>
        </tr>
        <tr>
          <td>張日貴</td>
          <td>屏東縣滿州鄉</td>
          <td>
            <a target="_" href="http://musiciantw.ncfta.gov.tw/list.aspx?p=M064&amp;c=&amp;t=1"
            >連結</a>
          </td>
          <td>1933-，滿州鄉民謠歌手、民謠傳藝師。2012年獲選文化部「重要傳統藝術－滿州民謠保存者」，之後受聘擔任傳藝師。</td>
        </tr>
        <tr>
          <td>許麗善</td>
          <td>屏東縣滿州鄉</td>
          <td></td>
          <td>1965-，擅長滿州民謠。文化部指定「重要無形文化資產保存者」張日貴之傳習藝生。現任屏東縣屏南社區大學副校長。</td>
        </tr>
        <tr>
          <td>黎竹紅</td>
          <td>屏東縣滿州鄉</td>
          <td></td>
          <td>1959，擅長滿州民謠。文化部指定「重要無形文化資產保存者」張日貴之傳習藝生。</td>
        </tr>
        <tr>
          <td>戴曉君</td>
          <td>屏東縣牡丹鄉</td>
          <td>
            <a target="_" href="https://www.facebook.com/TaiSiaoChun/">連結</a>
          </td>
          <td>1986-，創作歌手。將排灣古謠旋律融入音樂創作。2011、2014年兩度獲得「原創流行音樂大獎－原住民語組」首獎。</td>
        </tr>
        <tr>
          <td>曾仲影</td>
          <td>新北市</td>
          <td></td>
          <td>1922-，本名曾麒麟。作曲家、電影配樂、導演。2017年「新北文化貢獻獎」得獎人。畢生在歌仔戲、流行音樂、電影配樂及導演之文化領域中努力。從事電影配樂二十餘年，完成650餘首流行音樂的創作與編曲。</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>