<template>
  <div>
    <!-- <div class="title">
      <h2>客家音樂篇</h2>
    </div>
    <hr> -->
    <p class="firstRow"></p>
    <h3>一、客家傳統歌謠</h3>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:15%">負責人</th>
          <th style="width:28%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>基隆市客家文化協會</td>
          <td>黃成燈</td>
          <td>
            基隆市信義區信二路241號2樓
            <br>02-2421-3331
          </td>
          <td></td>
          <td>團練時間：每週五19:30-21:30</td>
        </tr>
        <tr>
          <td>三興客家歌謠班</td>
          <td>
            班長
            黃永柯
          </td>
          <td>臺北市信義區基隆路二段99號(三興國小)</td>
          <td></td>
          <td>1989年1月1日成立</td>
        </tr>
        <tr>
          <td>台北市客家自強會</td>
          <td>黃秋鳯</td>
          <td>
            臺北市中正區和平西路二段70巷8弄8號<br>
            彭智勇 02-2303-4875
          </td>
          <td>
            <a target="_" href="mailto:khome.pan@msa.hinet.net">連結</a>
          </td>
          <td>1991年成立</td>
        </tr>
        <tr>
          <td>台灣客家山歌團</td>
          <td>姜雲玉</td>
          <td>
            臺北市仁愛路四段345巷4弄39號4樓
            <br>02-2771-0794
          </td>
          <td></td>
          <td>團練時間：每週三14:00-17:00</td>
        </tr>
        <tr>
          <td>全球客家聲韻歌劇團</td>
          <td>張堂珍</td>
          <td>
            臺北市北投區明德路174巷8號2樓
            <br>02-2820-8756
          </td>
          <td>
            <a target="_" href="mailto:lifechang8@gmail.com">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>忠勤客家歌謠班</td>
          <td>彭維熙</td>
          <td>
            臺北市中正區中華路二段293號地下1樓(忠勤活動中心)
            <br>0937-920-246
          </td>
          <td></td>
          <td>團練時間：每週三19:30-21:30</td>
        </tr>
        <tr>
          <td>忠義客家歌謠班</td>
          <td>李榮堂</td>
          <td>
            臺北市中正區中華路二段315巷4弄1 號(國盛活動中心)
            <br>02-2307-2265
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>景美客家歌謠班</td>
          <td>陳錦月</td>
          <td>
            臺北市文山區羅斯福路6段393號7樓(景行活動中心)
            <br>02-2937-5272
          </td>
          <td></td>
          <td>團練時間：每週一19:00-21:00</td>
        </tr>
        <tr>
          <td>臺北市中原客家崇正會祟正歌謠班</td>
          <td>許瑞</td>
          <td>
            臺北市大安區信義路三段157巷11號4樓
            <br>0921-831-786
          </td>
          <td>
            <a target="_" href="mailto:ho2104@gmail.com">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>樟新客家歌謠班</td>
          <td>戴紅櫻</td>
          <td>
            臺北市文山區一壽街22號9樓(樟新活動中心)
            <br>02-2936-7260
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>關渡客家歌謠班</td>
          <td>黃順平</td>
          <td>
            02-2809-9036
          </td>
          <td></td>
          <td>2002年2月21日成立</td>
        </tr>
        <tr>
          <td>新北市傳統音樂發展協會</td>
          <td>羅文芳</td>
          <td>
            新北市板橋區民生路一段2號3樓
            <br>02-2978-4647
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>桃園市客家民謠研究學會</td>
          <td>黃金通</td>
          <td>
            桃園市中壢區元化路165巷17號9樓
            <br>03-426-5648
          </td>
          <td></td>
          <td>2015年成立</td>
        </tr>
        <tr>
          <td>碧霞鄉土客家民謠劇團</td>
          <td>趙彩雲</td>
          <td>
            桃園市中壢區三光路158巷12號
            <br>0912-671-732
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LBCCTY/">連結</a>
          </td>
          <td>2005年9月9日成立</td>
        </tr>
        <tr>
          <td>新竹縣新埔鎮客家民謠推廣協會</td>
          <td>鄭煥達</td>
          <td>
            新竹縣新埔鎮五埔里5鄰石坑街40巷10號
            <br>03-588-7323
          </td>
          <td></td>
          <td>1993年7月4日成立</td>
        </tr>
        <tr>
          <td>苗栗縣公館鄉石墻社區發展協會</td>
          <td>黃文欽</td>
          <td>
            苗栗縣公館鄉石墻村9鄰185-1號
            <br>邱新和 03-722-8136
          </td>
          <td></td>
          <td>1973年2月10日成立</td>
        </tr>
        <tr>
          <td>苗栗縣音樂發展協進會</td>
          <td>魏琬庭</td>
          <td>
            苗栗縣苗栗市文山里10鄰文興街1號
            <br>03-733-1258
          </td>
          <td></td>
          <td>2010年9月8日成立</td>
        </tr>
        <tr>
          <td>苗栗縣泰安歌舞發展協會</td>
          <td>黃文煥</td>
          <td>
            苗栗縣泰安鄉清安村1鄰洗水坑5號
            <br>0937-729-055
          </td>
          <td>
            <a target="_" href="mailto:kan@taian.gov.tw">連結</a>
          </td>
          <td>2000年4月16日成立</td>
        </tr>
        <tr>
          <td>東勢區農會客家傳統弦樂歌謠班</td>
          <td>
            班長
            何朝文
          </td>
          <td>
            臺中市東勢區豐勢路297號 (東勢區農會推廣部)
            <br>0921-730-057
          </td>
          <td></td>
          <td>1998年10月成立</td>
        </tr>
        <tr>
          <td>臺中市東勢區弘韻婦女音樂協進會</td>
          <td>李吳金蘭</td>
          <td>
            臺中市東勢區南平里本街193號
            <br>04-2587-3559
          </td>
          <td></td>
          <td>2007年成立</td>
        </tr>
        <tr>
          <td>臺中市客家文化協進會</td>
          <td>許勝明</td>
          <td>
            臺中市北屯區東光里16鄰北屯路296-25號
            <br>0930-878-768
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>府城哈客混聲合唱團</td>
          <td>謝佩芬</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>臺南市南瀛客家文化協會歌謠班</td>
          <td>謝錦梅</td>
          <td>
            臺南市新營區民權路96-27號
            <br>06-633-7627
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>臺南市客家文化協會客家歌謠班</td>
          <td>巫月雲</td>
          <td>
            臺南市新營區民權路96-27號
            <br>06-633-7627
          </td>
          <td></td>
          <td>2016年4月13日籌組，2017年1月10日登記立案，練習時間：每週三21:00-23:00。</td>
        </tr>
        <tr>
          <td>臺南市緣圓園客家樂舞團</td>
          <td>涂喜妹</td>
          <td>
            臺南市南區新孝路102巷43號
            <br>0932-987-889
          </td>
          <td></td>
          <td>2009年成立</td>
        </tr>
        <tr>
          <td>高雄市客屬美濃同鄉會月光山合唱團</td>
          <td>陳宏生</td>
          <td>
            高雄市三民區覺民路363號(民族國中)
            <br>07-323-8121
          </td>
          <td></td>
          <td>2007年成立</td>
        </tr>
        <tr>
          <td>月荷綜藝團</td>
          <td>鍾柑泉</td>
          <td>
            高雄市楠梓區樂群路220號(加昌國小)
            <br>07-365-0917
            <br>0928-726-823
          </td>
          <td></td>
          <td>2010年成立</td>
        </tr>
        <tr>
          <td>好客文化藝術團</td>
          <td>劉順昌</td>
          <td></td>
          <td></td>
          <td>2006年成立</td>
        </tr>
        <tr>
          <td>欣采樂綜藝團</td>
          <td>張素珠</td>
          <td></td>
          <td>
            <a target="_" href="mailto:swiftlet@swiftlet.com.tw">連結</a>
          </td>
          <td>2013年7月10日成立</td>
        </tr>
        <tr>
          <td>美濃客家山歌班</td>
          <td>葉鍾金嬌</td>
          <td>
            07-681-6865
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>美濃婦女合唱團</td>
          <td>
            團長
            李雪光<br>
            行政總監
            劉蘭英
          </td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/hklee0321/">連結</a>
          </td>
          <td>2007年成立</td>
        </tr>
        <tr>
          <td>真情綜藝團</td>
          <td>鍾柑泉</td>
          <td>
            高雄市楠梓區德賢路160號
            <br>0928-726-823
          </td>
          <td></td>
          <td>2014年成立</td>
        </tr>
        <tr>
          <td>高雄市山城客家藝術團</td>
          <td>鄧洲正</td>
          <td>
            高雄市新興區七賢二路68號
            <br>07-287-1135
          </td>
          <td></td>
          <td>2003年12月18日成立</td>
        </tr>
        <tr>
          <td>高雄市客家文化藝術團</td>
          <td>謝賜金</td>
          <td>
            高雄市前鎮區管仲路50巷44弄8號
            <br>0926-773-843
          </td>
          <td></td>
          <td>1986年10月1日成立</td>
        </tr>
        <tr>
          <td>高雄市客家民謠研究會</td>
          <td>劉黃運娣</td>
          <td>
            高雄市美濃區中興路一段147號
            <br>07-681-7890
          </td>
          <td></td>
          <td>2014年成立</td>
        </tr>
        <tr>
          <td>高雄市客家好音圓合唱團</td>
          <td>鍾政雄</td>
          <td>
            高雄市苓雅區建國一路354號(高雄道明中學)
            <br>0937-376-918
          </td>
          <td></td>
          <td>1999年9月27日成立</td>
        </tr>
        <tr>
          <td>高雄市客家鄉音樂團</td>
          <td>林梅芳</td>
          <td>
            高雄市新興區復橫一路241號<br>
            林榮貞 0953-338-726
          </td>
          <td></td>
          <td>2011年成立</td>
        </tr>
        <tr>
          <td>高雄市屏東客屬同鄉會歌謠班</td>
          <td>李達文</td>
          <td>
            高雄市中正三路28號5樓
            <br>0922-423-213
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>高雄市美濃客家混聲合唱團</td>
          <td>藍勝生</td>
          <td>
            高雄市美濃區泰安路228號
            <br>0933-661-823
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/高雄市美濃混聲合唱團-491930940887705/"
            >連結</a>
          </td>
          <td>2006年成立</td>
        </tr>
        <tr>
          <td>高雄市桂陽客家綜藝團</td>
          <td>曾招勤</td>
          <td>高雄市小港區桂陽路332號(桂林中厝聯合里活動中心)</td>
          <td></td>
          <td>1995年8月4日成立</td>
        </tr>
        <tr>
          <td>高雄市傳唱客家民俗藝團</td>
          <td>鍾桂香</td>
          <td></td>
          <td></td>
          <td>2004年3月25日成立</td>
        </tr>
        <tr>
          <td>菜公客家音樂協會(菜公民俗國樂團)</td>
          <td>葉木火</td>
          <td>
            高雄市左營區重立路280巷17號
            <br>0918-299-286
          </td>
          <td>
            <a target="_" href="http://kh19.khakka.org.tw/webeip/HT00567/kh19.asp"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>樂線綜藝團</td>
          <td>鍾鳳英</td>
          <td>
            高雄市三民區建工路433巷27號3樓
            <br>0922-233-283
          </td>
          <td></td>
          <td>2013年成立</td>
        </tr>
        <tr>
          <td>大路關山歌班</td>
          <td>溫智博</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>世客文化藝術團</td>
          <td>吳川鈴</td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/世客文化藝術團-336912869758607/"
            >連結</a>
          </td>
          <td>1995年成立</td>
        </tr>
        <tr>
          <td>世客屏東歌謠班</td>
          <td>吳川鈴</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>李文古歌劇團</td>
          <td>李盛發</td>
          <td>
            0932-882-984
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LiWenGuGeJuTuan/"
            >連結</a>
          </td>
          <td>1996年成立</td>
        </tr>
        <tr>
          <td>長治客家樂舞團(原名：長治客家歌謠班)</td>
          <td>胡新旗</td>
          <td>
            屏東縣長治鄉新潭村新民街106巷7號
            <br>08-738-2600
          </td>
          <td>
            <a target="_" href="mailto:hwushin066@yahoo.com.tw">連結</a>
          </td>
          <td>2000年成立</td>
        </tr>
        <tr>
          <td>長治崙上社區發展協會客家歌謠班</td>
          <td>馮昭麟</td>
          <td></td>
          <td></td>
          <td>2002年成立</td>
        </tr>
        <tr>
          <td>屏東客家樂舞團</td>
          <td>林瑞輝</td>
          <td>
            08-781-2456
            <br>0929-355-368
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/PTHakka/">連結</a>
          </td>
          <td>2001年成立</td>
        </tr>
        <tr>
          <td>屏東縣內埔鄉新北勢客家歌謠協會</td>
          <td>鍾貴梅</td>
          <td>
            屏東縣內埔鄉振豐村懷忠路79號
            <br>08-778-3212
          </td>
          <td></td>
          <td>1992年成立</td>
        </tr>
        <tr>
          <td>屏東縣六堆山歌研究促進會</td>
          <td>謝秋雄</td>
          <td>屏東縣新埤鄉建功村建功路140號</td>
          <td></td>
          <td>1992年成立</td>
        </tr>
        <tr>
          <td>屏東縣六堆客家歌謠舞蹈協會</td>
          <td>邱坤發</td>
          <td>
            屏東縣內埔鄉東勢村大同路南一巷22號
            <br>08-779-6816
            <br>08-779-3623
          </td>
          <td></td>
          <td>2001年成立</td>
        </tr>
        <tr>
          <td>屏東縣長治鄉客家民謠協會</td>
          <td>邱盛元</td>
          <td>
            08-721-7930
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>屏東縣長治鄉進興社區發展協會歌謠班</td>
          <td>馮昭麟</td>
          <td></td>
          <td></td>
          <td>2002年成立</td>
        </tr>
        <tr>
          <td>屏東縣長治鄉德協村歌謠班</td>
          <td>邱盛元</td>
          <td>
            08-721-7930
          </td>
          <td></td>
          <td>2002年成立</td>
        </tr>
        <tr>
          <td>屏東縣屏北社區大學歌謠班長治分班</td>
          <td>范家豪</td>
          <td></td>
          <td></td>
          <td>1995年成立</td>
        </tr>
        <tr>
          <td>屏東縣新埤鄉客家歌謠促進會</td>
          <td>鍾昭勤</td>
          <td>
            屏東縣新埤鄉建功村建成巷41號
            <br>08-797-1673
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>屏東縣潮州鎮客家文化推廣協會</td>
          <td>劉麗珍</td>
          <td>
            屏東縣潮州鎮中山路38號
            <br>08-789-1062
          </td>
          <td></td>
          <td>1998年成立</td>
        </tr>
        <tr>
          <td>美和新故鄉樂舞團</td>
          <td>李少華</td>
          <td>
            屏東縣內埔鄉和興村學人路618巷45弄46號
            <br>08-778-4378
          </td>
          <td></td>
          <td>2006年成立</td>
        </tr>
        <tr>
          <td>慈恩客家樂舞團</td>
          <td>鄭達正</td>
          <td>
            屏東縣竹田鄉美崙村忠崙路12號
            <br>08-779-3493
          </td>
          <td></td>
          <td>1993年成立</td>
        </tr>
        <tr>
          <td>藍衫樂舞團</td>
          <td>鍾芳廉</td>
          <td>
            0929-090-581
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/藍衫樂舞團-Blue-Shirts-Music-and-Dance-Troupe-185867531445580/"
            >連結</a>
          </td>
          <td>2007年11月27日成立</td>
        </tr>
        <tr>
          <td>花蓮客家合唱團</td>
          <td>李惠敏</td>
          <td>
            0933-997-800
          </td>
          <td>
            <a target="_" href="mailto:Grace0933997800@gmail.com">連結</a>
          </td>
          <td>2006年8月31日成立，練習時間：每週四19:00-21:00。</td>
        </tr>
        <tr>
          <td>花蓮縣瑞穗鄉富源社區客家歌謠班</td>
          <td>黃遠龍</td>
          <td>
            花蓮縣瑞穗鄉富源村富源路2-1號(富源社區常民文化館)<br>
            指導老師：鍾湧春 0933-998-328
          </td>
          <td>
            <a target="_" href="http://www.web66.com.tw/CW123/花蓮縣瑞穗鄉富源社區發展協會-B123480.html"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>台東縣民俗音樂聚英研究社</td>
          <td>張菊霖</td>
          <td>
            臺東縣臺東市大同路254號
            <br>0937-390-607
          </td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
    <br>
    <h3>二、客家傳統器樂(八音、北管、國樂)</h3>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:10%">負責人</th>
          <th style="width:30%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>台北正心箏樂團</td>
          <td>魏德棟</td>
          <td>
            臺北市和平東路三段49號10樓之3
            <br>02-2704-7208
          </td>
          <td>
            <a target="_" href="mailto:weiderdon101@gmail.com">連結</a>
          </td>
          <td>1977年成立</td>
        </tr>
        <tr>
          <td>鄉音國樂團</td>
          <td>許瑞</td>
          <td>
            臺北市信義路三段157巷11號4樓
            <br>0921-831-786
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/hakkamelody/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>榮芳客家北管國樂團</td>
          <td>陳石榮</td>
          <td>新北市樹林區太平路89號</td>
          <td></td>
          <td>2004年成立</td>
        </tr>
        <tr>
          <td>大華國樂文創團</td>
          <td>陳國芳</td>
          <td>
            桃園市八德區介壽路二段1022巷14號
            <br>0935-025-143
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/大華國樂文創團陳國芳-1563159900469333/"
            >連結</a>
          </td>
          <td>2000年成立</td>
        </tr>
        <tr>
          <td>和成八音團</td>
          <td>袁久貴</td>
          <td>
            桃園市八德區霄裡里官路缺街53號
            <br>0910-150-749
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Hcg2232/">連結</a>
          </td>
          <td>1994年成立</td>
        </tr>
        <tr>
          <td>田屋北管八音團</td>
          <td>田文光</td>
          <td>田文龍 03-551-3320</td>
          <td>
            <a target="_" href="https://www.facebook.com/TienWuBeiGuanBaYin/"
            >連結</a>
          </td>
          <td>1921年成立</td>
        </tr>
        <tr>
          <td>乾興客家八音團</td>
          <td>陳焜全</td>
          <td>
            新竹縣湖口鄉湖南村15鄰乾興路180巷5號
            <br>03-569-1852
          </td>
          <td>
            <a target="_" href="https://m.facebook.com/陳四源祖堂祭祀公業法人新竹縣陳乾興-172956626411473/"
            >連結</a>
          </td>
          <td>2012年成立</td>
        </tr>
        <tr>
          <td>新竹紅如國樂團</td>
          <td>莊紅如</td>
          <td>
            0915-222-137
          </td>
          <td>
            <a target="_" href="https://m.facebook.com/紅如樂團Hung-Ru-Music-Group-703386793013859/"
            >連結</a><br>
            <a target="_" href="mailto:fn4286@yahoo.com.tw">連結</a>
          </td>
          <td>2002年3月15日成立</td>
        </tr>
        <tr>
          <td>苗栗陳家班北管八音團</td>
          <td>鄭榮興</td>
          <td>
            苗栗縣苗栗市後龍鎮豐富里新東路47-1號
            <br>03-772-5099
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/MiaoliChenFamilyBeiguanBayinTroupe/"
            >連結</a>
          </td>
          <td>1945年成立</td>
        </tr>
        <tr>
          <td>竹頭背客家八音團</td>
          <td>鍾兆生</td>
          <td>
            高雄市美濃區廣興街121號
            <br>07-681-2538
          </td>
          <td>
            <a target="_" href="mailto:p6812538@gmail.com">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>林作長客家八音團</td>
          <td>林作長</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>美濃客家八音團</td>
          <td>鍾彩祥</td>
          <td>
            高雄市美濃區泰中路259巷23號
            <br>07-682-2348
            <br>謝宜文 0932-837-873
          </td>
          <td>
            <a target="_" href="mailto:anmiwen@gmail.com">連結</a>
          </td>
          <td>2006年成立</td>
        </tr>
        <tr>
          <td>陳美子客家八音團</td>
          <td>陳美子</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>溫福仁客家八音團</td>
          <td>溫福仁</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>鍾雲輝客家八音團</td>
          <td>鍾雲輝</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>大夥房藝術團</td>
          <td>劉國政</td>
          <td>
            屏東縣麟洛鄉新田村民族路234號
            <br>08-723-1258
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/大夥房藝術團-1371254872966824/"
            >連結</a>
          </td>
          <td>2002年成立</td>
        </tr>
        <tr>
          <td>池新客家山歌樂團</td>
          <td>何國光</td>
          <td>
            臺東縣池上鄉新興村5鄰57-3號
            <br>089-863-200
            <br>0919-128-119
          </td>
          <td></td>
          <td>2007年成立</td>
        </tr>
        <tr>
          <td>德興社客家八音團</td>
          <td></td>
          <td>
            臺東縣關山鎮德高里2鄰永豐11號
            <br>詹坤桂 0937-391-433
          </td>
          <td></td>
          <td>1937年成立</td>
        </tr>
      </tbody>
    </table>
    <br>
    <h3>三、客家傳統戲曲與表演形式</h3>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th>名稱</th>
          <th>負責人</th>
          <th>地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:15%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>星韻創意合唱團</td>
          <td>林明明</td>
          <td>
            臺北市萬華區康定路46-2號
            <br>02-2331-8292<br>
          彭智勇 0936-069-079
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/星韻創意合唱團-563743170344180/"
            >連結</a>
          </td>
          <td>指導老師：徐韻絜</td>
        </tr>
        <tr>
          <td>紙風車劇團</td>
          <td>李永豐</td>
          <td>
            臺北市重慶南路二段59-2號2樓
            <br>02-2392-6170
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/paperwindmilltheatre/"
            >連結</a>
          </td>
          <td>1992年成立</td>
        </tr>
        <tr>
          <td>國立臺灣戲曲學院客家戲學系</td>
          <td>
            系主任
            劉麗株
          </td>
          <td>
            臺北市木柵路三段66巷8-1號
            <br>02-2936-7231#2551
          </td>
          <td>
            <a target="_" href="http://b017.tcpa.edu.tw/bin/home.php">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>山宛然客家布袋戲團</td>
          <td>黃武山</td>
          <td>
            新北市板橋區縣民大道三段83號3樓
            <br>0932-330-003
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/山宛然客家布袋戲團-193976375896/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>美江舞蹈團</td>
          <td>郭美江</td>
          <td>
            新北市永和區竹林路76號4樓
            <br>02-2557-5320
          </td>
          <td>
            <a target="_" href="mailto:mei_chiang1204@yahoo.com.tw">連結</a>
          </td>
          <td>1977年成立</td>
        </tr>
        <tr>
          <td>戲偶子劇團</td>
          <td>邱豐榮</td>
          <td>
            新北市新店區達觀路38號2樓之6
            <br>02-221-38657
            <br>0975-386-935
          </td>
          <td>
            <a target="_" href="http://www.playpuppet.com.tw/home.html">連結</a>
          </td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>金龍戲劇團</td>
          <td>鄭長庚</td>
          <td>
            0900-227-056
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/金龍戲劇總團-196943617329245/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>景勝戲劇團</td>
          <td>江玉玲</td>
          <td>
            0935-129-811
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/景勝戲劇團-1657899551112033/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>貴鳳歌劇團</td>
          <td>陳鳳祺</td>
          <td>
            0911-241-388
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/a241388/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>新月娥歌劇團</td>
          <td>劉雅如</td>
          <td>
            桃園市楊梅區民豐路68巷6弄6號
            <br>0933-507-453
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/新月娥歌劇團-334133613587392/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>德泰戲劇團</td>
          <td>李小平</td>
          <td>
            桃園市中壢區龍岡路三段243巷53弄36號
            <br>03-458-6287
            <br>0919-362-104
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/a034586287/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>松興戲劇團</td>
          <td>林松興</td>
          <td>
            新竹縣北埔鄉中山路51號
            <br>0916-333-293
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/song.xing.opera/"
            >連結</a>
          </td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>新永光歌劇團</td>
          <td>翁義富</td>
          <td></td>
          <td></td>
          <td>1962年成立</td>
        </tr>
        <tr>
          <td>新樂園戲劇團</td>
          <td>劉秀鳳</td>
          <td>
            新竹縣竹北市縣政三街19號
            <br>03-555-6358
          </td>
          <td></td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>霓雲社客家三腳採茶戲團</td>
          <td>徐進堯</td>
          <td></td>
          <td>
            <a target="_" href="mailto:ctl.wang@msa.hinet.net">連結</a>
          </td>
          <td>1996年成立</td>
        </tr>
        <tr>
          <td>金滿圓戲劇團</td>
          <td>管建仲</td>
          <td>苗栗縣苗栗市福星里16鄰華清街9號</td>
          <td></td>
          <td>1999年成立</td>
        </tr>
        <tr>
          <td>苗栗縣客家曲藝推展協會</td>
          <td>謝其國</td>
          <td>
            0937-813-833
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>榮興採茶劇團</td>
          <td>鄭月景</td>
          <td>
            苗栗縣苗栗市恭敬里4鄰恭敬路46巷5號
            <br>03-772-5099
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/romshinghakka/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>廖千盛布袋戲團</td>
          <td>廖千盛</td>
          <td>
            雲林縣二崙鄉崙東村仁和路142巷27號
            <br>05-598-8188
          </td>
          <td></td>
          <td>2013年成立</td>
        </tr>
        <tr>
          <td>廖千順布袋戲團</td>
          <td>廖千順</td>
          <td>
            雲林縣二崙鄉三和村三和路28-49號
            <br>0933-509-888
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>廖文和布袋戲團</td>
          <td>廖文和</td>
          <td>
            雲林縣二崙鄉紹興路19號
            <br>05-598-3777
            <br>0933-499-999
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/wen.holiao/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>走馬蓋文化藝術團</td>
          <td>楊秀春</td>
          <td>
            高雄市前鎮區瑞祥里崗山中街255號4樓之2
            <br>0931-616-986
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>哈旗鼓文化藝術團</td>
          <td>李榮豐</td>
          <td>
            高雄市前鎮區崗山中街255號4樓之1
            <br>楊秀春 0931-616-986
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HaChiGu/">連結</a>
          </td>
          <td>2004年2月成立</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>