<template>
  <div>
    <!-- <div class="title">
      <h2>南管音樂篇</h2>
    </div>
    <hr> -->
    <p class="firstRow"></p>
    <h3>一、南管團體</h3>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">地址/電話</th>
          <th style="width:10%">其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>閩南第一樂團南管研究中心</td>
          <td>呂光輝</td>
          <td>
            基隆市孝西路10號之2 陸橋下
            <br>02-2424-1308
            <br>0937-880-367
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/217228464957550/"
            >連結</a>
          </td>
          <td>
            基府教演字第036號，負責人呂光輝亦為南管組組長，農曆初一、十五有祀王唱曲活動。
          </td>
        </tr>
        <tr>
          <td>閩南南樂演藝團</td>
          <td>黃玉梅</td>
          <td>02-2465-2075</td>
          <td></td>
          <td>以習南管戲為主</td>
        </tr>
        <tr>
          <td>大稻埕戲苑南管班</td>
          <td>林珀姬<br>徐智城</td>
          <td>大稻埕戲苑</td>
          <td>
            <a target="_" href="https://www.facebook.com/dadaochen2011/"
            >連結</a>
          </td>
          <td>上課時間：每週二晚上，報名請洽大稻埕戲苑南管班。</td>
        </tr>
        <tr>
          <td>中華絃館研究團</td>
          <td>莊國章</td>
          <td>
            臺北市八德路三段27號2樓 山韻樂器行
            <br>02-2577-5518
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/中華絃管研究團-328596864328765/"
            >連結</a>
          </td>
          <td>目前以松山社大傳習為主體</td>
        </tr>
        <tr>
          <td>心心南管樂坊</td>
          <td>王心心</td>
          <td>
            臺北市大同區興城街10巷16號
            <br>02-2557-8239
            <br>02-2557-8907(傳真)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/NanguanXinXin/"
            >連結</a>
          </td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>和鳴南樂社</td>
          <td>魏秀蓉</td>
          <td>
            臺北市南京西路344巷2號M樓(臺北法主公廟)
            <br>02-2556-2964(臺北法主公廟)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/和鳴南樂社-He-Ming-Nanguan-Ensemble-南管館閣-175327956220495/"
            >連結</a>
          </td>
          <td>1997年成立 上課時間：每週一、四晚上；拍館時間：每週五。</td>
        </tr>
        <tr>
          <td>青和南管</td>
          <td>魏伯年</td>
          <td>臺北市士林區承德路四段177號</td>
          <td>
            <a target="_" href="https://www.facebook.com/qhnanguan/">連結</a>
          </td>
          <td>
            士林社區大學報名電話：02-2880-6580；
            <br>上課時間：每週一晚上，
            教師魏伯年、駱惠賢。
          </td>
        </tr>
        <tr>
          <td>華聲南樂團</td>
          <td>
            負責人 蕭志恆
            <br>團長 鄭靜芬
          </td>
          <td>
            臺北市延平北路1段22號6樓之2(登記地址)
            <br>臺北市承德路三段54號4樓(通訊地址)
            <br>02-25950070(聯絡人：翁瓊華)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HuaSiengNanGuan/"
            >連結</a>
          </td>
          <td>
            1985年創團，穩定成長，老團員多位已有三十年以上學習歷史；教師林珀姬。
          </td>
        </tr>
        <tr>
          <td>詠吟南樂社</td>
          <td>團長 何欽龍</td>
          <td>
            臺北市撫遠街380巷14號4樓
            <br>02-2766-2603
          </td>
          <td></td>
          <td>2004年成立，團長何欽龍、教師林珀姬。</td>
        </tr>
        <tr>
          <td>福壽宮南樂社</td>
          <td>團長 陳銘富</td>
          <td>臺北市敦煌路2-1號(大龍峒福壽宮)</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>閩南樂府南管研究社</td>
          <td>呂進發</td>
          <td>
            臺北市延平北路三段61巷32號2樓
            <br>02-2591-1302
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/台北市閩南樂府弦管研究會-2196238770415810/"
            >連結</a>
          </td>
          <td>拍館時間：每週六晚上，總幹事呂瑞華。</td>
        </tr>
        <tr>
          <td>永和南樂社</td>
          <td>陳宗碑</td>
          <td>
            新北市永和區勵行街44號3樓
            <br>02-2921-2866
          </td>
          <td></td>
          <td>每週一、三、五晚上活動，現改名為永和體育協會南樂社。</td>
        </tr>
        <tr>
          <td>南薰閣</td>
          <td>徐智城</td>
          <td>新北市板橋區館前東路116號6樓之12</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>江之翠劇場</td>
          <td>魏美慧</td>
          <td>臺北市遼寧街185巷7弄3號1樓(藝響空間)</td>
          <td></td>
          <td>江之翠團員重新登記組團，2018年有《行過洛津》一劇演出。</td>
        </tr>
        <tr>
          <td>浯江南樂社</td>
          <td>李國俊</td>
          <td>
            新北市永和區中正路527號8樓之1
            <br>02-2231-0006
          </td>
          <td></td>
          <td>每週六晚上活動，以金門同鄉為主。</td>
        </tr>
        <tr>
          <td>淡水清音社</td>
          <td>李巧芸</td>
          <td>新北市淡水區學府路99號(上課地點：鄧公國小教室)</td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/danshuinanguan/about/?ref=page_internal"
            >連結</a>
          </td>
          <td>社長李巧芸、教師徐智城，上課時間：每週一19:00-21:00。</td>
        </tr>
        <tr>
          <td>漢唐樂府</td>
          <td>陳美娥</td>
          <td>
            新北市淡水區自強路287-1號6樓
            <br>02-2809-3890
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/漢唐樂府-HanTang-YueFu-184122174945933/"
            >連結</a>
          </td>
          <td>為專業演藝團體，成員為家族式，兼習梨園戲，並以現代劇場呈現傳統曲藝。王阿心於2002年(民91)離開漢唐樂府，自創心心南管樂府。</td>
        </tr>
        <tr>
          <td>閩聲社</td>
          <td>余火城</td>
          <td>
            新竹市中南街38號
            <br>03-522-8253
          </td>
          <td></td>
          <td>無活動</td>
        </tr>
        <tr>
          <td>中瀛南樂社</td>
          <td>陳枝財</td>
          <td>
            04-2277-8665
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>文昌公廟南管團</td>
          <td>黃珠玲</td>
          <td>
            臺中市南屯區南屯里文昌街100號
            <br>04-2389-1827
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/台中南屯文昌公廟南管樂團-1590780834504047/about/?ref=page_internal"
            >連結</a>
          </td>
          <td>
            1998年(民87)成立；
            <br>上課時間：每週六14:00-16:00，由蔡崑山指導。
          </td>
        </tr>
        <tr>
          <td>臺中水碓南管樂坊(善德堂南樂社)</td>
          <td>社長 劉欽沂</td>
          <td>
            臺中市南屯區水碓巷1號(永春東三路與環中路五段交叉口)
            <br>04-2479-2217
            <br>0937-296-905
          </td>
          <td></td>
          <td>
            教師馬一瑚、理事長陳光耀；
            <br>練習時間：每週二19:30-21:30。
          </td>
        </tr>
        <tr>
          <td>合和藝苑</td>
          <td>吳素霞</td>
          <td>
            臺中市沙鹿區北勢二街21鄰10巷26號
            <br>04-2652-6631
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/合和藝苑-579899192117301/"
            >連結</a>
          </td>
          <td>1999年成立，以傳承七子戲前後場為主。</td>
        </tr>
        <tr>
          <td>長隆南樂社</td>
          <td>
            團長 吳素霞
            <br>副團長 吳炳慧
          </td>
          <td>臺中市</td>
          <td>
            <a target="_" href="https://www.facebook.com/profile.php?id=100002456890010"
            >連結</a>
          </td>
          <td>傳承七子戲前場與南管音樂，副團長吳炳慧為南管戲人間國寶吳素霞之第一屆結業藝生。</td>
        </tr>
        <tr>
          <td>清雅樂府</td>
          <td>黃珠玲</td>
          <td>
            臺中市清水區鎮新路298巷11號(館址)
            <br>臺中市清水區大街路206號(活動地點：紫雲巖4樓)
            <br>04-2623-2422
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Taichung.CHING.YA.YUEH.FU/"
            >連結</a>
          </td>
          <td>興旺，兼傳習七子戲，吳素霞於2000年(民89)離開，自創合和藝苑。</td>
        </tr>
        <tr>
          <td>聚雅齋</td>
          <td>吳敏彥</td>
          <td>
            臺中市大甲區城隍廟
            <br>04-687-3364
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>樂成宮南樂社</td>
          <td>周芳麗</td>
          <td>臺中市東區旱溪街48號(樂成宮)</td>
          <td>
            <a target="_" href="https://www.facebook.com/profile.php?id=100000501913312"
            >連結</a>
          </td>
          <td>南管音樂</td>
        </tr>
        <tr>
          <td>龍天宮南管樂府</td>
          <td>鄭洪員</td>
          <td>臺中市龍井區龍天宮</td>
          <td>
            <a target="_" href="https://www.facebook.com/profile.php?id=100008301367221"
            >連結</a>
          </td>
          <td>南管音樂</td>
        </tr>
        <tr>
          <td>永樂弦管</td>
          <td>林秋菊</td>
          <td>
            彰化縣鹿港鎮福德祠
            <br>04-775-4848
          </td>
          <td></td>
          <td>暫無活動，參與遏雲齋活動。</td>
        </tr>
        <tr>
          <td>雅正齋</td>
          <td>董建林</td>
          <td>
            彰化縣鹿港鎮老人會
            <br>04-777-5514
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/618296004968390/"
            >連結</a>
          </td>
          <td>臺灣最古老的館閣，至少有300年歷史。</td>
        </tr>
        <tr>
          <td>遏雲齋</td>
          <td>郭元湧</td>
          <td>
            彰化縣鹿港鎮八德路149 號 (曲館)
            <br>彰化縣鹿港鎮郭厝里郭厝巷147號
            <br>04-778-5787
            <br>04-777-5660
            <br>04-777-3566 (陳逢南)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/鹿港遏雲齋南管樂團-180173595360938/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>彰化南北戲曲館研習班</td>
          <td>
            甲班 魏美慧
            <br>乙班 郭元湧
            <br>丙班 施永川
            <br>丁班 許耀升
          </td>
          <td>
            彰化市平和7街66號 (南北管音樂戲曲館，甲乙丙三班)
            <br>彰化縣鹿港鎮龍山寺 (丁班)
            <br>電話：04-751-0709#104
            <br>傳真：04-751-0753
          </td>
          <td></td>
          <td>詳細資訊與報名請洽彰化縣文化局南北管音樂戲曲館</td>
        </tr>
        <tr>
          <td>彰化縣文化局南管實驗樂團</td>
          <td>教師 吳素霞</td>
          <td>
            彰化市平和7街66號(南北管音樂戲曲館)
            <br>電話：04-751-0709#104
            <br>傳真：04-751-0753
          </td>
          <td></td>
          <td>南北管音樂戲曲館</td>
        </tr>
        <tr>
          <td>聚英社</td>
          <td>許耀升<br>施永川</td>
          <td>
            彰化縣鹿港鎮金門街81號(龍山寺)
            <br>04-726-3817
            <br>04-778-6775
            <br>04-781-1299
            <br>0935-224-100
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LKnankuan/">連結</a>
            <br>
            <a target="_" href="mailto:tyu666888@yahoo.com.tw">連結</a>
          </td>
          <td>現多為年輕人。平日分鹿港、彰化二地練習，興習假日回鹿港龍山寺合樂。</td>
        </tr>
        <tr>
          <td>臺中永盛樂府/彰化縣美港西社區大學</td>
          <td>教師 朱永勝</td>
          <td>彰化縣伸港鄉泉州社區活動中心</td>
          <td>
            <a target="_" href="https://www.facebook.com/yongsheng.zhu1"
            >連結</a>
          </td>
          <td>上課時間：每週六13:30，報名請洽彰化美港西社區大學。</td>
        </tr>
        <tr>
          <td>錦成閣</td>
          <td>昌錦龍</td>
          <td>
            彰化縣埔鹽鄉大新路2巷53號
            <br>0933-172-601
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>北港集斌社</td>
          <td>許澤猛</td>
          <td>
            雲林縣北港鎮華勝路130號(通訊地址)
            <br>05-783-4085
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/集斌社-274917685886071/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>汾雅齋</td>
          <td>
            教師 王淑珍 蔡清源
            <br>社長 李平印
          </td>
          <td>
            雲林縣北港鎮文化路214號
            <br>0921-029-778
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/nanguan.fen.ye/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>青雲閣</td>
          <td>黃輝煌</td>
          <td>嘉義縣朴子市中正路179號 黃宅</td>
          <td></td>
          <td>少活動</td>
        </tr>
        <tr>
          <td>鳳聲閣</td>
          <td>蔡清源</td>
          <td>
            嘉義市永安街364號1樓
            <br>05-236-4133
            <br>0921-330292(沈怡秀)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/鳳聲閣-559488677847210/"
            >連結</a>
          </td>
          <td>上課時間：每週五18:30，嘉義南管研習班。</td>
        </tr>
        <tr>
          <td>和聲社</td>
          <td>杜清蔭</td>
          <td>
            臺南市灣裡路282巷38號(慶安宮)
            <br>06-262-0536
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Wanli.Lamim/">連結</a>
          </td>
          <td>每週一、二、五晚上活動。</td>
        </tr>
        <tr>
          <td>南聲社</td>
          <td>林毓汀</td>
          <td>
            臺南市南區仁南街水門宮內2樓
            <br>06-263-3929
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tainannanshan/"
            >連結</a>
          </td>
          <td>興旺，每週三、六晚上活動。</td>
        </tr>
        <tr>
          <td>振東社</td>
          <td></td>
          <td>臺南市學甲區池府王爺廟</td>
          <td></td>
          <td>已無活動</td>
        </tr>
        <tr>
          <td>振聲社</td>
          <td>蔡芬得</td>
          <td>
            臺南市忠孝街112號(媽祖樓前)
            <br>電話：06-228-9473
            <br>傳真：06-259-1593
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TNtsinsingsia/"
            >連結</a>
            <a target="_" href="mailto:tsai.fente@msa.hinet.net">連結</a>
          </td>
          <td>1996年(民85)恢復活動，每週六、日下午活動。</td>
        </tr>
        <tr>
          <td>清和社</td>
          <td>吳庚生</td>
          <td>臺南市安定區海寮普陀寺</td>
          <td>
            <a target="_" href="https://www.facebook.com/海寮南樂清和社-1555814204633359/"
            >連結</a>
          </td>
          <td>目前成員有23人，每週四、五20:00-21:30由資深館員帶領進行練習。</td>
        </tr>
        <tr>
          <td>喜樹國小南管班</td>
          <td>
            校長 王龍雄
            <br>主任 黃懷慧
          </td>
          <td>
            臺南市南區喜樹路133號
            <br>06-262-2462
          </td>
          <td></td>
          <td>教師張栢仲</td>
        </tr>
        <tr>
          <td>新聲社</td>
          <td></td>
          <td>臺南市關廟區松仔村</td>
          <td></td>
          <td>無活動，館址樂器俱在。</td>
        </tr>
        <tr>
          <td>臺南大天后宮以群社南音團</td>
          <td>楊慧容、王美珠</td>
          <td>
            臺南市中西區永福路二段227巷18號
            <br>0922-497-641(楊慧容)
            <br>0985-459-924(王美珠)
          </td>
          <td></td>
          <td>曾聘請泉州南樂團李白燕短期教學，上課時間：每週五、六20:00-22:00。</td>
        </tr>
        <tr>
          <td>正聲社</td>
          <td></td>
          <td>高雄市茄萣區正順廟</td>
          <td></td>
          <td>配合廟會活動學習</td>
        </tr>
        <tr>
          <td>光安南樂社</td>
          <td>洪進益</td>
          <td>
            高雄市楠梓區右昌三仙街38號
            <br>07-362-2115
          </td>
          <td></td>
          <td>目前活動力強，年輕館員企圖心強，音樂表現有相當的水準。</td>
        </tr>
        <tr>
          <td>串門南樂社</td>
          <td>鄭德慶</td>
          <td>高雄市民享街102號</td>
          <td></td>
          <td>以卓聖翔、林素梅二人為主。</td>
        </tr>
        <tr>
          <td>振南社</td>
          <td>薛寶源</td>
          <td>高雄市茄萣區金鑾宮</td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/225183657584348/"
            >連結</a>
          </td>
          <td>配合廟會活動學習。</td>
        </tr>
        <tr>
          <td>振樂社</td>
          <td></td>
          <td>高雄市茄萣區賜福宮</td>
          <td></td>
          <td>配合廟會活動學習。</td>
        </tr>
        <tr>
          <td>集賢社</td>
          <td>顏秋琴</td>
          <td>
            高雄市左營區
            <br>07-582-3206
          </td>
          <td></td>
          <td>少活動，廟會時仍組團參加。</td>
        </tr>
        <tr>
          <td>集聲南樂社</td>
          <td></td>
          <td>高雄市內門區內豐村內埔82號(紫竹寺)</td>
          <td></td>
          <td>農曆初一、十五祀觀音唱曲活動，平日已無活動。</td>
        </tr>
        <tr>
          <td>新興社</td>
          <td>劉良思</td>
          <td>
            高雄市內門區內門103號
            <br>06-667-3655
          </td>
          <td></td>
          <td>練習時間：每週六、日09:30-11:30。</td>
        </tr>
        <tr>
          <td>聚雲社</td>
          <td></td>
          <td>
            高雄市梓官區梓官路(義氣堂)
            <br>07-610-3567
          </td>
          <td></td>
          <td>尚有春秋二祭，但少與外界交陪。</td>
        </tr>
        <tr>
          <td>廣益南樂社</td>
          <td>許丁春</td>
          <td>
            高雄市大社區民生路32號
            <br>07-351-0581
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/GuangYiNanYue/"
            >連結</a>
          </td>
          <td>原太平歌館集興軒改學洞管</td>
        </tr>
        <tr>
          <td>醉仙亭南樂社</td>
          <td></td>
          <td>高雄市鳳山區文雅東街150號</td>
          <td></td>
          <td>農曆初一、十五唱曲祀觀音，不對外活動。</td>
        </tr>
        <tr>
          <td>薦善南樂社</td>
          <td></td>
          <td>
            高雄市阿蓮區民族路82巷14號
            <br>電話：07-631-2058
            <br>傳真：07-632-1317
            <br>曲館：07-631-9870
          </td>
          <td></td>
          <td>每日晚間活動，每週六休息。</td>
        </tr>
        <tr>
          <td>鎮海宮南樂社</td>
          <td>洪全瑞</td>
          <td>
            屏東縣東港鎮鎮海路42-5號(鎮海宮)
            <br>08-832-4667
            <br>08-832-7777(鎮海宮)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/JHENHAIKUNG.NUNKUAN/"
            >連結</a>
          </td>
          <td>原為南管小唱，現改習洞管。</td>
        </tr>
        <tr>
          <td>聚英社</td>
          <td>吳曙崗<br>謝旭日</td>
          <td>
            臺東市博愛路421號2樓
            <br>08-934-2531
            <br>089-235-212(謝旭日)
            <br>0922-455-733(謝旭日)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/139815092737543/"
            >連結</a>
          </td>
          <td>每週六下午活動</td>
        </tr>
        <tr>
          <td>金沙南樂社</td>
          <td>張國強<br>教師 陳金潭</td>
          <td>金門縣金沙鎮沙美勝利路25巷1號(金沙長青活動中心)</td>
          <td></td>
          <td>練習時間：每週六、日09:30-11:30。</td>
        </tr>
        <tr>
          <td>金門南樂研究社</td>
          <td>徐聲良<br>陳七二</td>
          <td>金門縣金城城隍廟內右廂房</td>
          <td></td>
          <td>無活動，徐聲良至金門樂府活動。</td>
        </tr>
        <tr>
          <td>金門碧山仙洲南樂研習社</td>
          <td>陳榮泰</td>
          <td>碧山活動中心</td>
          <td></td>
          <td>新成立，由來自泉州的教師吳淑珍指導，練習時間：每週六、日09:30-11:30。</td>
        </tr>
        <tr>
          <td>金門樂府</td>
          <td>許虎</td>
          <td>金城體育館</td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/176691215689013/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>浯江南樂研習社</td>
          <td>陳亞福</td>
          <td>
            金沙活動中心
            <br>08-235-2611
          </td>
          <td></td>
          <td>由來自泉州的教師吳淑珍指導，練習時間：每週六、日09:30-11:30。</td>
        </tr>
        <tr>
          <td>烈嶼群聲南樂社</td>
          <td>洪清發</td>
          <td>
            金門縣烈嶼鄉西路60號
            <br>08-236-2223
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>澎湖西瀛南樂社</td>
          <td>蘇菁萍</td>
          <td>
            澎湖縣馬公市中華路230號 (澎湖縣文化局南管研習班)
            <br>電話：06-926-1141#4
            <br>傳真：06-927-6602
          </td>
          <td>
            <a target="_" href="mailto:ph1141@ms2.hinet.net">連結</a><br>
            <a target="_" href="mailto:geosu5438@yahoo.com.tw">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>澎湖縣集慶堂南樂協會</td>
          <td>蔡明紅</td>
          <td>
            澎湖縣馬公市新村路18號
            <br>電話：06-926-8221
            <br>傳真：06-927-6602
          </td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
    <br>
    <h3>二、太平歌</h3>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th>名稱</th>
          <th>負責人</th>
          <th>地址/電話</th>
          <th>其他聯絡方式</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>公親寮清水寺天子門生</td>
          <td>吳清吉</td>
          <td>臺南市安南區公學路一段228號</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>永吉吉安宮天子門生</td>
          <td>曾海燈</td>
          <td>
            臺南市七股區永吉里1鄰16-9號(吉安宮)
            <br>06-787-2024(吉安宮)
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>麻豆巷口集英社太平清歌</td>
          <td>郭武驥 陳灼琴 李金堂</td>
          <td>臺南市麻豆區巷口里和平路3號(慶安宮)</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>港墘港興宮天子門生</td>
          <td>黃玉惠</td>
          <td>臺南市佳里區通興里港墘1-2號</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>竹橋慶善宮牛犁歌陣</td>
          <td>黃薇芬</td>
          <td>
            臺南市七股區竹橋里130號(竹橋國小)
            <br>臺南市七股區竹橋里竹橋35號(慶善宮)
            <br>06-789-1041#20(竹橋國小)
            <br>06-789-3978 (慶善宮)
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>金鑾宮太平歌樂社</td>
          <td>郭江清</td>
          <td>
            高雄市茄萣區保定里港東街111號
            <br>07-690-2948
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>烏山坑牛犁陣</td>
          <td>楊正源</td>
          <td>高雄市內門區光興村</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>番仔路和樂軒太平歌陣</td>
          <td>鄭永辰</td>
          <td>
            高雄市內門區觀亭村番子路25之1號
            <br>0936-767-856
            <br>07-667-4427
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>鴨母寮太平歌</td>
          <td>林和順</td>
          <td>
            高雄市內門區光興里鴨母寮16號
            <br>07-667-2257
          </td>
          <td></td>
          <td>練習時間：每週五19:30-22:00。</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>