<template>
  <div>
    <!-- <div class="title">
      <h2>北管音樂篇</h2>
    </div>
    <hr> -->
    <p class="firstRow"></p>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>暖暖靈義郡</td>
          <td></td>
          <td>基隆市暖暖區</td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/1720303424908310/about/"
            >連結</a>
          </td>
          <td>前名為「興義軒」，1859年成立，1862年改名為靈義郡，2018/07/29舉辦160週年遶境。</td>
        </tr>
        <tr>
          <td>中華民國傳統民俗文化協會</td>
          <td>理事長 謝志烽</td>
          <td>
            基隆市仁愛區孝三路60號3樓
            <br>02-2422-3826
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/lnheritance/">連結</a>
          </td>
          <td>
            2015年成立，每週五13:00 - 15:00
            於安樂高中授課，活動中亦有免費指導成人北管樂器練習，歡迎民眾參加。
          </td>
        </tr>
        <tr>
          <td>得意堂十組</td>
          <td>大隊長謝煌璿</td>
          <td>基隆市仁愛區仁三路27-2號</td>
          <td>
            <a target="_" href="https://www.facebook.com/DenjiPalace/">連結</a>
          </td>
          <td>隸屬基隆市奠濟宮</td>
        </tr>
        <tr>
          <td>聚樂社一組</td>
          <td>林平侯</td>
          <td>
            基隆市仁愛區新店里忠一路7號(基隆城隍廟)
            <br>基隆市仁愛區忠二路1號(基隆慶安宮)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/基隆聚樂社一組-1632638547021049/"
            >連結</a>
          </td>
          <td>約1851年-1861年間成立，練習時間：每週三、六14:30-17:00。</td>
        </tr>
        <tr>
          <td>永樂軒</td>
          <td>李正宗</td>
          <td>02-2766-3012(松山慈祐宮)</td>
          <td>
            <a target="_" href="https://www.facebook.com/YongLexuan/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>永興軒</td>
          <td>王正雄</td>
          <td>臺北市汀州路三段77號(永興宮)</td>
          <td>
            <a target="_" href="https://www.facebook.com/LOVE500211/">連結</a>
          </td>
          <td>1947年底成立，1952年正式安館。</td>
        </tr>
        <tr>
          <td>共樂軒</td>
          <td>顏輝龍</td>
          <td>
            臺北市大同區民樂街68-1號
            <br>02-2553-6501
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TaipeiGongLeXuan/"
            >連結</a>
          </td>
          <td>1911年成立，練習時間：每週五19:30。</td>
        </tr>
        <tr>
          <td>成樂社</td>
          <td>黃健龍</td>
          <td>
            臺北市大同區延平北路三段18巷32號
            <br>0960-057-271
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/1017227034959961/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>和華樂社</td>
          <td>李世澤</td>
          <td>
            臺北市大同區迪化街二段350號
            <br>02-2595-8872
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/164928970295214/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>保安社</td>
          <td>連進益</td>
          <td>臺北市大同區迪化街2段304號(萬和宮旁)</td>
          <td>
            <a target="_" href="https://www.facebook.com/1445771065744156/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>保安宮北管團</td>
          <td>保安宮</td>
          <td>
            臺北市大同區哈密街61號(大龍峒保安宮紫薇閣2樓)
            <br>02-2595-1676
          </td>
          <td>
            <a target="_" href="http://www.baoan.org.tw/asp/Learning/learning-class-1.asp"
            >連結</a>
          </td>
          <td>每年2月，8月招生，每年3月，9月開課。上課時間：週四18:30-21:00。</td>
        </tr>
        <tr>
          <td>國立臺北藝術大學傳統音樂學系</td>
          <td>蔡淩蕙</td>
          <td>
            臺北市北投區學園路1號
            <br>02-2896-7294
          </td>
          <td>
            <a target="_" href="https://trd-music.tnua.edu.tw/"
            >連結</a>
          </td>
          <td>1995年成立，設有北管樂主修。</td>
        </tr>
        <tr>
          <td>集思小劇坊</td>
          <td>蔡婷如</td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/Brainstromworkshop/"
            >連結</a>
          </td>
          <td>由臺北藝術大學傳統音樂學系校友組成，演出內容包含南、北管。</td>
        </tr>
        <tr>
          <td>新樂社</td>
          <td>陳碧玉</td>
          <td>臺北市北投區</td>
          <td>
            <a target="_" href="https://www.facebook.com/newmusicsir/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>會安樂社</td>
          <td>林添訓</td>
          <td>
            臺北市松山區市民大道四段71號
            <br>02-2751-5609
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/kuei580922/">連結</a>
          </td>
          <td>北管部分由淡水、三芝師兄弟支援，神將組由板橋北極壇支援，不定期進行團練。</td>
        </tr>
        <tr>
          <td>福樂社</td>
          <td></td>
          <td>臺北市松山區</td>
          <td>
            <a target="_" href="https://www.facebook.com/SongShanFuLeShe/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>靈安社</td>
          <td>
            社長 周淑穗
            <br>總幹事 吳柏勳
          </td>
          <td>
            臺北市大同區歸綏街116號
            <br>02-2557-4855
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/linganshe/">連結</a>
          </td>
          <td>練習時間：每週一(牌子)、三(戲曲)19:30-21:30。</td>
        </tr>
        <tr>
          <td>三芝協和軒</td>
          <td>張秀子</td>
          <td>新北市三芝區古庄里</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>三重南義社</td>
          <td>周俊德</td>
          <td>
            新北市三重區三光街56號(倉庫)
            <br>新北市三重區新北大道一段46巷7號(團址/臨水宮)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/SanZhongNanYiShe/"
            >連結</a>
          </td>
          <td>6月開始，每週三19:30 - 21:30練習。</td>
        </tr>
        <tr>
          <td>中和清和社</td>
          <td>林志勝</td>
          <td>新北市中和區圓通路296巷1-1號(高架橋下)</td>
          <td>
            <a target="_" href="https://www.facebook.com/NiubuChildren/"
            >連結</a>
          </td>
          <td>練習時間：每週五19:30。</td>
        </tr>
        <tr>
          <td>丹鳳高中國中部北管團</td>
          <td></td>
          <td>
            新北市新莊區龍安路72號
            <br>02-2908-9627
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/丹鳳新聲北管-564010327385642/"
            >連結</a>
          </td>
          <td>2017年10月成立，由楊晨琦指導。</td>
        </tr>
        <tr>
          <td>汐止樂英社</td>
          <td>詹光明</td>
          <td>新北市汐止區</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>屈尺國興社</td>
          <td>唐健煌</td>
          <td>
            新北市新店區屈尺路66號3樓(聯絡處)、 新北市新店區屈尺路125號
            (練習地/屈尺岐山巖)
          </td>
          <td></td>
          <td>約1981年成立，練習時間不定，有時間的話一週2-3天，於19:30-21:00練習。</td>
        </tr>
        <tr>
          <td>延樂軒北管劇團</td>
          <td>林永志</td>
          <td>
            新北市八里區頂寮二街121巷18之28號
            <br>02-2618-2448
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tw.peikuan/">連結</a>
          </td>
          <td>2008-2014年連續獲選為(今)新北市扶植團隊、2014年新北市政府文化局傑出演藝團隊。</td>
        </tr>
        <tr>
          <td>板橋福安社</td>
          <td>陳志成</td>
          <td>新北市金門街336巷7號左側(溪福市民活動中心)</td>
          <td>
            <a target="_" href="https://www.facebook.com/板橋福安社-351768694985876/"
            >連結</a>
          </td>
          <td>每週一、三晚上練習，由張天培指導。</td>
        </tr>
        <tr>
          <td>板橋聚安社</td>
          <td>執行長 詹志添</td>
          <td>
            新北市板橋區大觀路二段163號(浮州福德宮)
            <br>02-2968-5386(浮州福德宮)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/板橋聚安社-496550503732647/"
            >連結</a>
          </td>
          <td>每週二、五19:30-21:30。</td>
        </tr>
        <tr>
          <td>板橋潮和社</td>
          <td>李滿雄(副社長)</td>
          <td>
            新北市板橋區溪頭街356號
            <br>02-2252-7379
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/板橋潮和社-363071557084558/"
            >連結</a>
          </td>
          <td>練習時間：每週一、三、五20:00-22:00。</td>
        </tr>
        <tr>
          <td>林口中興社</td>
          <td></td>
          <td>新北市林口永善寺</td>
          <td>
            <a target="_" href="https://www.facebook.com/林口中興社-657469964339295/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>林口平樂社</td>
          <td>謝林凱</td>
          <td>新北市林口區太平里2鄰</td>
          <td>
            <a target="_" href="https://www.facebook.com/481788695352176/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>林口洪福社</td>
          <td>李永昌</td>
          <td>新北市林口區下福139之11號(洪福宮)</td>
          <td>
            <a target="_" href="https://www.facebook.com/244hongfu/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>林口悅樂軒</td>
          <td>黃清火</td>
          <td>新北市林口區</td>
          <td></td>
          <td>每週三、四練習。</td>
        </tr>
        <tr>
          <td>林口復興社</td>
          <td>謝春富</td>
          <td>新北市林口區</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>林口福樂社</td>
          <td></td>
          <td>新北市林口區</td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/975444539145292/photos/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>林口樂林園</td>
          <td>林春生</td>
          <td>
            新北市林口區自強三街28號(林口贊天宮)
            <br>02-2601-3756
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/286379778180151/"
            >連結</a>
          </td>
          <td>暑假每週三、六排練，週日弦樂班研習。</td>
        </tr>
        <tr>
          <td>林口寶樂軒</td>
          <td>李金燦</td>
          <td>新北市林口區寶斗厝坑</td>
          <td>
            <a target="_" href="https://www.facebook.com/729204547105694/"
            >連結</a>
          </td>
          <td>每週三、四練習。</td>
        </tr>
        <tr>
          <td>林口顯林社</td>
          <td>蘇裔輝</td>
          <td>新北市林口區頂福20之16號(林口顯應祖師廟)</td>
          <td>
            <a target="_" href="https://www.facebook.com/sdkksdb820330/"
            >連結</a>
          </td>
          <td>每週六、日練習。</td>
        </tr>
        <tr>
          <td>金山三界壇北管和樂社</td>
          <td>徐文讓</td>
          <td>
            新北市金山區三界壇路58巷3號
            <br>0981-825-559(賴先生)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/SANJIETANHEYUESHE/"
            >連結</a>
          </td>
          <td>
            練習時間：每週六14:30於 金包里社區發展協會
            (新北市金山區大同里溫泉路2巷9號)。
          </td>
        </tr>
        <tr>
          <td>淡水和義軒</td>
          <td>郭鑽榮</td>
          <td>新北市淡水區清水街127號</td>
          <td>
            <a target="_" href="https://www.facebook.com/QingShui127club/"
            >連結</a>
          </td>
          <td>1913年成立，練習時間：每週六19:00-21:00。</td>
        </tr>
        <tr>
          <td>淡水保安社</td>
          <td>洪興旺</td>
          <td>
            新北市淡水區淡海路189巷(沙崙保安廟)
            <br>02-2805-5947
          </td>
          <td></td>
          <td>無團練，每年農曆正月初六固定出陣。</td>
        </tr>
        <tr>
          <td>淡水南北軒</td>
          <td>吳明華</td>
          <td>
            新北市淡水區公明街21號(舊館)
            <br>新北市淡水區仁愛街15-4號(新館)
            <br>02-2621-2442
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tamsui.beiguan/"
            >連結</a>
          </td>
          <td>1917年成立，練習時間：每週日19:00-21:00。</td>
        </tr>
        <tr>
          <td>菁桐里南極社</td>
          <td>潘淑璟</td>
          <td>
            新北市平溪區
            <br>0910-050-373(李國豪)
            <br>0932-924-017(潘淑璟)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Jtnjs/">連結</a>
          </td>
          <td>1986年成立，團員大約40人，每月練習3-4天，練習時間13:00-16:00。</td>
        </tr>
        <tr>
          <td>菁桐聚樂社女子一組</td>
          <td>王月蓮</td>
          <td>
            新北市平溪區
            <br>0932-241-608
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Taipei.Chingtung.Women1group/"
            >連結</a>
          </td>
          <td>1970年成立，團員16人。</td>
        </tr>
        <tr>
          <td>新莊新樂園</td>
          <td>楊乾德</td>
          <td>
            新北市新莊區新樹路17號2樓(聯絡處)
            <br>新北市新莊區新莊路727號(館址)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/XinZhuangXinLeYuan/"
            >連結</a>
          </td>
          <td>1921年成立，練習時間每週一、四19:30-21:30。</td>
        </tr>
        <tr>
          <td>大溪同義社</td>
          <td></td>
          <td>桃園市大溪區</td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/1424579577797914/about/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>大溪琴書堂</td>
          <td></td>
          <td>桃園市大溪區</td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/387743514658493/about/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>大溪農作團</td>
          <td></td>
          <td>桃園市大溪區</td>
          <td>
            <a target="_" href="https://www.facebook.com/大溪農作團-580208425435071/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>同芯社</td>
          <td>古先生</td>
          <td>
            桃園市中壢區
            <br>0935-516-012
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/桃園同芯社北管樂團-515221688507319/"
            >連結</a>
          </td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>同義軒</td>
          <td>李宗翰</td>
          <td>桃園市八德區</td>
          <td>
            <a target="_" href="https://www.facebook.com/356982231120776/"
            >連結</a>
          </td>
          <td>練習時間：每週一、三19:30。</td>
        </tr>
        <tr>
          <td>鈞天社</td>
          <td>北管部部長 林建利</td>
          <td>
            桃園市桃園區中正路208號
            <br>0928-295-280
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/桃園鈞天社-北管部-123281811170392/"
            >連結</a>
          </td>
          <td>桃園鈞天社位於桃園景福宮內，為景福宮之主要社團。</td>
        </tr>
        <tr>
          <td>竹塹北管藝術團</td>
          <td>林金偕團長</td>
          <td>新竹市中山路75號03-526-6077</td>
          <td>
            <a target="_" href="https://www.facebook.com/TikTshamPakKuan/"
            >連結</a>
          </td>
          <td>練習時間：每週五、六19:30-22:00鑼鼓嗩吶班，每週日14:00-17:00絃樂班。</td>
        </tr>
        <tr>
          <td>後龍共樂軒</td>
          <td>
            余神威
            <br>
          </td>
          <td>
            苗栗縣後龍鎮三民路120號(慈雲宮)
            <br>03-772-2367
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>田心長樂軒</td>
          <td>賴添華</td>
          <td>
            臺中市南屯區大墩五街328號2樓
            <br>0912-037-889
          </td>
          <td>
            <a target="_" href="mailto:lai88168168@yahoo.com.tw">連結</a>
          </td>
          <td>1998年成立，練習時間每週一、三、五19:00-21:00。</td>
        </tr>
        <tr>
          <td>何厝新樂軒北管樂團</td>
          <td>何山陽</td>
          <td>
            臺中市西屯區臺灣大道二段826號
            <br>0937-295-493(吳佳鞠)
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/何厝-新樂軒北管樂團-405637472825452/"
            >連結</a>
          </td>
          <td>1935年(昭和十年)創立，練習時間每週一19:30-21:00。</td>
        </tr>
        <tr>
          <td>明梨園北管團</td>
          <td>林先生</td>
          <td>
            臺中巿太平區
            <br>0928-341-355
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/臺中太平-明梨園北管團-116056275101395/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>南屯景樂軒</td>
          <td>林志源</td>
          <td>臺中市南屯區</td>
          <td>
            <a target="_" href="https://www.facebook.com/151200718262888/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>振梨園</td>
          <td>江振吉</td>
          <td>
            臺中市東區十甲路24-2號
            <br>0932-622-629
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/振梨園-139735242776111/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>㩳愉轃北管掌中實驗團</td>
          <td>蕭任能</td>
          <td>南投縣草屯鎮建國街28號</td>
          <td>
            <a target="_" href="https://www.facebook.com/㩳愉轃北管掌中實驗團-2277122652371830/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>玉琴軒北管樂團</td>
          <td>主委 許森樹</td>
          <td>彰化縣鹿港鎮街尾里力行街2號</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>和美成樂軒</td>
          <td>鄭夏苗</td>
          <td>彰化縣和美鎮</td>
          <td>
            <a target="_" href="https://www.facebook.com/彰化和美成樂軒北管樂團-1866548670244089/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>花壇御夆閣亂彈劇團</td>
          <td>吳炳榮</td>
          <td>
            彰化縣花壇鄉長沙村彰員路二段801號
            <br>04-786-3360
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/DaDi.DaDi.DaDaDi/"
            >連結</a>
          </td>
          <td>2017年成立，練習時間每週一、四晚上、週日下午。</td>
        </tr>
        <tr>
          <td>南瑤宮勵英社</td>
          <td>李秋風</td>
          <td>彰化縣彰化市南瑤路43號(南瑤宮)</td>
          <td>
            <a target="_" href="https://www.facebook.com/彰化南瑤宮勵英社北管-1429140743771145/"
            >連結</a>
          </td>
          <td>練習時間每週一、三19:00-21:00。</td>
        </tr>
        <tr>
          <td>梨芳園北管樂團</td>
          <td>巫玉柱</td>
          <td>
            彰化市西勢里忠勢巷2號(聖安宮)
            <br>04-762-8975
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/梨芳園-403860836310480/"
            >連結</a>
          </td>
          <td>1833年成立(道光十三年)，練習時間，每週一、三、五晚上。</td>
        </tr>
        <tr>
          <td>梨春園北管樂團</td>
          <td>葉金泉</td>
          <td>
            彰化市民權里華山路138巷51號
            <br>04-726-4337
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Lichunyuanbeiguan/"
            >連結</a>
          </td>
          <td>1811年成立，每週一至六19:30-21:30。</td>
        </tr>
        <tr>
          <td>圓仔花樂團</td>
          <td>倪珩均</td>
          <td>
            彰化縣和美鎮西園路331巷178號
            <br>0972-093-757
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/InnahueBand/">連結</a>
          </td>
          <td>2017年成立，每月兩次練習，練習內容有北管音樂及樂團創作作品。</td>
        </tr>
        <tr>
          <td>彰化縣文化局北管實驗樂團</td>
          <td></td>
          <td>
            彰化市崙平里平和七街66號
            <br>04-751-0753
          </td>
          <td></td>
          <td>2000年成立</td>
        </tr>
        <tr>
          <td>榮樂軒北管劇團</td>
          <td>游榮石</td>
          <td>彰化市福成街63巷2號</td>
          <td>
            <a target="_" href="https://www.facebook.com/彰化阿夷庄-榮樂軒北管-298142537001837/"
            >連結</a>
          </td>
          <td>1933年創館，練習時間每週一至五19:00-21:00。</td>
        </tr>
        <tr>
          <td>鳳儀園北管樂團</td>
          <td>魏坤慶</td>
          <td>彰化市崙平里北館街19-1號(崙聖宮2樓)</td>
          <td>
            <a target="_" href="https://www.facebook.com/new3mazu/">連結</a>
          </td>
          <td>1871年(同治十年)成立，練習時段每週一、三、四晚上。</td>
        </tr>
        <tr>
          <td>灣仔口玉鳳園</td>
          <td>李隨清</td>
          <td>
            彰化縣花壇鄉灣雅村彰員路一段838號
            <br>04-787-5360
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/yufengyuan/about/"
            >連結</a>
          </td>
          <td>每週一、三19:00-21:00，蘇皇誌指導。</td>
        </tr>
        <tr>
          <td>集雅軒</td>
          <td>李連春</td>
          <td>雲林縣北港鎮博愛路62號</td>
          <td>
            <a target="_" href="https://www.facebook.com/BgTraditionalopera/"
            >連結</a>
          </td>
          <td>1853年成立，目前固定每週三練習。</td>
        </tr>
        <tr>
          <td>社團法人金聲順古樂協會</td>
          <td>林延樺</td>
          <td>0952-669-808</td>
          <td>
            <a target="_" href="https://www.facebook.com/jinshengshun/">連結</a>
          </td>
          <td>北港朝天宮開路鼓</td>
        </tr>
        <tr>
          <td>大林銧樂軒</td>
          <td>蘇皇誌</td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/嘉義銧樂軒-771286676312015/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>內田慶和軒</td>
          <td>黃錦財</td>
          <td>
            嘉義縣布袋鎮見龍里180之35號
            <br>0919-864-413
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/profile.php?id=100005080484012"
            >連結</a>
          </td>
          <td>進階班每週二、四、六上課，初階班每週一、三、五上課；由黃錦財與大師兄邱丁進共同指導。</td>
        </tr>
        <tr>
          <td>新港國小北管團</td>
          <td></td>
          <td>
            嘉義縣新港鄉登雲路105號
            <br>05-374-2039
          </td>
          <td></td>
          <td>由舞鳳軒陳朝江指導</td>
        </tr>
        <tr>
          <td>新港舞鳳軒北管戲劇團</td>
          <td>二師兄 陳朝江</td>
          <td>嘉義縣新港鄉新民路115號</td>
          <td></td>
          <td>約西元1820年成立，每週二、四19:30-21:00於奉天宮練習。</td>
        </tr>
        <tr>
          <td>溪北六興軒</td>
          <td>陳建信</td>
          <td>
            嘉義縣新港鄉溪北村65號(溪北六興宮)
            <br>05-377-1042
          </td>
          <td></td>
          <td>溪北六興宮義工組成的北管團，中斷數十年後於2011年重新復館。現為每週日上課，由內田慶和軒大師兄邱丁進指導。</td>
        </tr>
        <tr>
          <td>慶順境</td>
          <td>楊茗傑</td>
          <td>
            臺南市善化區
            <br>0985-679-128
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Tainan.Ching.Shuen.Jing/"
            >連結</a>
          </td>
          <td>北管落地吹，成團約兩年。</td>
        </tr>
        <tr>
          <td>慶樂社</td>
          <td>陳懋陞</td>
          <td>臺南市<br>0933-333-611</td>
          <td>
            <a target="_" href="https://www.facebook.com/台南慶樂社-194025980638369/"
            >連結</a>
          </td>
          <td>排場、落地吹、鼓亭、北管、潮州鑼鼓。</td>
        </tr>
        <tr>
          <td>鎮樂社</td>
          <td>陳家全</td>
          <td>
            臺南市北區
            <br>0927-147-705
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/鎮樂社-262394460486479/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>灣里彩雲軒</td>
          <td>灣裡萬年殿</td>
          <td>
            臺南市南區灣裡路64號
            <br>06-262-2668
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>茄萣金鑾宮北管振樂軒</td>
          <td>金鑾宮</td>
          <td>
            高雄市茄萣區保定里港東街111號
            <br>07-690-5997
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/jinluangung/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>德興軒</td>
          <td>陳禹佑</td>
          <td>
            高雄市前鎮區
            <br>0953-335-636
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/高雄德興軒-1601808163239490/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>大漢樂團</td>
          <td>樂團總監 何彥勳</td>
          <td>
            屏東縣東港鎮東隆街21-1號(東港東隆宮)
            <br>08-833-3182
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/東港東隆宮大漢樂團-青少年組-281513001991101/"
            >連結</a>
          </td>
          <td>每週三、五、六19:00-21:00練習。</td>
        </tr>
        <tr>
          <td>屏東峰岳閣</td>
          <td>陳志峰</td>
          <td>屏東縣萬丹鄉新鐘村新鐘路75號</td>
          <td>
            <a target="_" href="https://www.facebook.com/167235153374685"
            >連結</a>
          </td>
          <td>練習時間：每週三晚上。</td>
        </tr>
        <tr>
          <td>屏東縣佳冬鄉昌隆國小</td>
          <td>張文忠</td>
          <td>屏東縣佳冬鄉昌隆村中正路44號<br>08-866-2093</td>
          <td>
            <a target="_" href="https://web.chles.ptc.edu.tw/school/web/index.php"
            >連結</a>
          </td>
          <td>由張日丸老師指導</td>
        </tr>
        <tr>
          <td>宜蘭復蘭社</td>
          <td>曾瓊萱</td>
          <td>宜蘭市</td>
          <td>
            <a target="_" href="https://www.facebook.com/宜蘭復蘭社-北管樂曲-118201122147561/"
            >連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>頂埔集蘭社</td>
          <td>梁鈜傑</td>
          <td>
            宜蘭縣頭城鎮
            <br>0903-597-793
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/頂埔集蘭社-215745202145819/"
            >連結</a>
          </td>
          <td>每週六、日19:30-21:30於葛瑪蘭救難協會練習。</td>
        </tr>
        <tr>
          <td>漢陽北管劇團</td>
          <td>陳玉環</td>
          <td>
            宜蘭縣頭城鎮開蘭路289巷8號
            <br>0911-217-268
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/漢陽北管劇團-393475427342892/"
            >連結</a>
          </td>
          <td>練習時間較機動，配合藝生跟演出場次。</td>
        </tr>
        <tr>
          <td>福蘭社</td>
          <td>陳虞鎰</td>
          <td>
            宜蘭縣羅東鎮中山西街113之1號
            <br>0927-507-456
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>羅東嘉興團</td>
          <td>簡進益</td>
          <td>
            宜蘭縣羅東鎮站前路56巷1號
            <br>0981-782-986
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/羅東嘉興團-1419673174915121/"
            >連結</a>
          </td>
          <td>1954年成立</td>
        </tr>
        <tr>
          <td>花蓮社</td>
          <td>莊萬春</td>
          <td>花蓮縣花蓮市</td>
          <td></td>
          <td>成立於日治時代，至今已有八十多年歷史，於1980年代中斷，2015年復社。每週二、四19:30練習。</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>