<template>
  <div>
    <div class="title">
      <h2>流行音樂</h2>
      <!-- <span>林珀姬</span> -->
    </div>
    <hr>
    <p class="firstRow"></p>
    <table rules="all" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th>名稱</th>
          <th>負責人</th>
          <th>地址/電話</th>
          <th>網址</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>MATZKA</td>
          <td>有凰音樂國際股份有限公司</td>
          <td>羅特國際製作股份有限公司02-2727-1977</td>
          <td>
            <a href="https://www.facebook.com/matzka2010/">https://www.facebook.com/matzka2010/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>Hit Fm聯播網</td>
          <td>Hit Fm聯播網</td>
          <td>
            臺北市中正區杭州南路一段15之一號1樓
            <br>02-2395-7255
          </td>
          <td></td>
          <td>1998年開播</td>
        </tr>
        <tr>
          <td>P!SCO</td>
          <td>P!SCO</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/piscoband/">https://www.facebook.com/piscoband/</a>
          </td>
          <td>2010年成立</td>
        </tr>
        <tr>
          <td>S.H.E</td>
          <td>華研國際音樂</td>
          <td>02-2512-1919</td>
          <td>
            <a href="https://www.facebook.com/shehimmusic/">https://www.facebook.com/shehimmusic/</a>
          </td>
          <td>2001年成立</td>
        </tr>
        <tr>
          <td>ゲシュタルト乙女</td>
          <td>ゲシュタルト乙女</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/GestaltGirl/">https://www.facebook.com/GestaltGirl/</a>
          </td>
          <td>2016年成立</td>
        </tr>
        <tr>
          <td>八三夭</td>
          <td>滾石唱片</td>
          <td>臺北市內湖區內湖路一段120巷17號2樓</td>
          <td>
            <a href="https://www.band831.com/">https://www.band831.com/</a>
          </td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>大象體操</td>
          <td>大象體操</td>
          <td></td>
          <td>
            <a
              href="https://www.instagram.com/elephant_gym_official/"
            >https://www.instagram.com/elephant_gym_official/</a>
          </td>
          <td>2012年成立</td>
        </tr>
        <tr>
          <td>五月天</td>
          <td>相信音樂股份有限公司</td>
          <td></td>
          <td>
            <a href="http://www.bin-music.com/">http://www.bin-music.com/</a>
          </td>
          <td>1997年成立</td>
        </tr>
        <tr>
          <td>文化部影視及流行音樂產業局</td>
          <td>徐宜君 局長</td>
          <td>
            臺北市中正區開封街1段3號
            <br>02-2375-8368
          </td>
          <td>
            <a href="https://www.bamid.gov.tw/">https://www.bamid.gov.tw/</a>
          </td>
          <td>2012年成立</td>
        </tr>
        <tr>
          <td>四分衛</td>
          <td>闊思音樂有限公司</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/quarterback.qb/"
            >https://www.facebook.com/quarterback.qb/</a>
          </td>
          <td>1993年成立</td>
        </tr>
        <tr>
          <td>生祥樂隊</td>
          <td>山下民謠</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/ShengXiangBand/"
            >https://www.facebook.com/ShengXiangBand/</a>
          </td>
          <td>1998年成立</td>
        </tr>
        <tr>
          <td>白目樂隊</td>
          <td>Indie</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/thewhiteeyesTW/"
            >https://www.facebook.com/thewhiteeyesTW/</a>
          </td>
          <td>2004年成立</td>
        </tr>
        <tr>
          <td>伍佰</td>
          <td>月光音樂</td>
          <td></td>
          <td>
            <a href="http://wubai.com/clubwubai/">http://wubai.com/clubwubai/</a>
          </td>
          <td>1990年出道</td>
        </tr>
        <tr>
          <td>好事花生</td>
          <td>好事花生</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/GoodNewsBand.tw/"
            >https://www.facebook.com/GoodNewsBand.tw/</a>
          </td>
          <td>2012年成立</td>
        </tr>
        <tr>
          <td>自然流動樂團</td>
          <td>阮丹青</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/SunshineCosta/"
            >https://www.facebook.com/SunshineCosta/</a>
          </td>
          <td>2009年成立</td>
        </tr>
        <tr>
          <td>血肉果汁機</td>
          <td>好球娛樂</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/fleshjuicer/">https://www.facebook.com/fleshjuicer/</a>
          </td>
          <td>2006年成立</td>
        </tr>
        <tr>
          <td>吳宗憲</td>
          <td>容易文創</td>
          <td>02-2755-3066</td>
          <td>
            <a href="mailto:easycc.ltd@gmail.com ">easycc.ltd@gmail.com</a>
            <br>
            <a
              href="https://www.facebook.com/jackywuofficial/"
            >https://www.facebook.com/jackywuofficial/</a>
          </td>
          <td>1987年出道</td>
        </tr>
        <tr>
          <td>沙沙小樂團</td>
          <td></td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/pg/sasalittleband/"
            >https://www.facebook.com/pg/sasalittleband/</a>
          </td>
          <td>2015年成立</td>
        </tr>
        <tr>
          <td>東京中央線</td>
          <td>山下民謠</td>
          <td></td>
          <td>
            <a href="https://tokyochuoline.com/">https://tokyochuoline.com/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>春麵樂隊</td>
          <td>春麵樂隊</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/春麵樂隊ChuNoodle-150724869107878/"
            >https://www.facebook.com/春麵樂隊ChuNoodle-150724869107878/</a>
          </td>
          <td>2018年成立</td>
        </tr>
        <tr>
          <td>茄子蛋</td>
          <td>經紀人百萱</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/EggPlantEgg/">https://www.facebook.com/EggPlantEgg/</a>
          </td>
          <td>2012年成立</td>
        </tr>
        <tr>
          <td>閃靈樂團</td>
          <td>環球唱片</td>
          <td></td>
          <td>
            <a href="https://chthonic.tw/">https://chthonic.tw/</a>
          </td>
          <td>1996年成立</td>
        </tr>
        <tr>
          <td>晨曦光廊</td>
          <td>晨曦光廊</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/SUNOFMORNING/">https://www.facebook.com/SUNOFMORNING/</a>
          </td>
          <td>2008年成立</td>
        </tr>
        <tr>
          <td>蛋堡</td>
          <td>顏社 KAO!INC.</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/Softlipa/">https://www.facebook.com/Softlipa/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>許郁瑛</td>
          <td>許郁瑛</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/yyhsu.music">https://www.facebook.com/yyhsu.music</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>陳明章</td>
          <td>陳明章</td>
          <td>
            臺北市北投區開明街71號
            <br>02-2893-3088
          </td>
          <td>
            <a
              href="https://www.facebook.com/Taiwan.yueqin/"
            >https://www.facebook.com/Taiwan.yueqin/</a>
          </td>
          <td>2009年成立</td>
        </tr>
        <tr>
          <td>雀斑樂團</td>
          <td></td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/frecklesarethebest"
            >https://www.facebook.com/frecklesarethebest</a>
          </td>
          <td>2003年成立</td>
        </tr>
        <tr>
          <td>彭佳慧</td>
          <td>索尼音樂</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/pg/juliastar888/"
            >https://www.facebook.com/pg/juliastar888/</a>
          </td>
          <td>1996年出道</td>
        </tr>
        <tr>
          <td>華昇</td>
          <td>華昇</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/HakkaWatson/">https://www.facebook.com/HakkaWatson/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>黃小琥</td>
          <td>星光娛樂</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/superTigerHuang/"
            >https://www.facebook.com/superTigerHuang/</a>
          </td>
          <td>1989年出道</td>
        </tr>
        <tr>
          <td>黃鴻升</td>
          <td>進化音樂娛樂</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/pg/aes.alien/">https://www.facebook.com/pg/aes.alien/</a>
          </td>
          <td>2002年出道</td>
        </tr>
        <tr>
          <td>黑旋風</td>
          <td>A&amp;E群藝國際娛樂有限公司</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/BlackTwoStorm/"
            >https://www.facebook.com/BlackTwoStorm/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>萬芳</td>
          <td>滾石唱片</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/pg/iamOneFang/"
            >https://www.facebook.com/pg/iamOneFang/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>詹姆士醫療團隊</td>
          <td>Dr.詹姆士</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/DrJamesMusic/">https://www.facebook.com/DrJamesMusic/</a>
          </td>
          <td>2012年成立</td>
        </tr>
        <tr>
          <td>詹雅雯</td>
          <td>詹雅雯</td>
          <td></td>
          <td>
            <a
              href="https://www.facebook.com/pg/YW.FanClub/"
            >https://www.facebook.com/pg/YW.FanClub/</a>
          </td>
          <td>1980年出道</td>
        </tr>
        <tr>
          <td>蔡秋鳳</td>
          <td>華特唱片</td>
          <td>02-2835-3418</td>
          <td>
            <a href="https://www.watermusic.com.tw/">https://www.watermusic.com.tw/</a>
          </td>
          <td>1978年出道</td>
        </tr>
        <tr>
          <td>蕭煌奇</td>
          <td>好莉嗨文創有限公司</td>
          <td>02-2364-8229</td>
          <td>
            <a href="mailto:huangchi0922@gmail.com">huangchi0922@gmail.com</a>
          </td>
          <td>1999年出道</td>
        </tr>
        <tr>
          <td>隨性樂團</td>
          <td></td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/RANDOM78/">https://www.facebook.com/RANDOM78/</a>
          </td>
          <td>2005年成立</td>
        </tr>
        <tr>
          <td>蘇珮卿</td>
          <td>蘇珮卿</td>
          <td></td>
          <td>
            <a href="https://www.facebook.com/su.paige/">https://www.facebook.com/su.paige/</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>董事長樂團</td>
          <td>獨一無二娛樂文化</td>
          <td>02-2651-9595</td>
          <td>
            <a
              href="https://www.facebook.com/chairman.taiwan/"
            >https://www.facebook.com/chairman.taiwan/</a>
          </td>
          <td>1997年成立</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>